suppressPackageStartupMessages({
  require(stringr)
  require(topicmodels)
  require(tm)
  require(dplyr)
  require(RCurl)
  require(text2vec)
  require(gtools)
})

#Define functions
stopwords = unique(c("div", "href", "rel", "com", "relnofollow", "про", "что","dneprcity.net","novostimira.com","depo.ua","bbc.com",
                     "для", "relnofollow", "alt", "zero","img", "alignleft", "hspace", "vspace","studic.info","description","delo.ua",
                     "alignleft", "hspace", "vspace", "pbrp","altновини", "hrefhttpgsfmopinionhtml", "mode","strong", "pstrong", "targetblank",
                     "styletext-align", "justifi","altнапк", "classattachment-decosingl", "classreadmor","http:img.ura","pigua.info",
                     "ethereum", "hrefhttpresonanceua", "hrefhttpsinforesistorg","replyua.net","newsoboz.org","mc.async","manabalss.lv",
                     "hrefhttpblogiuaus", "hrefhttpvycherpnockua", "hrefhttpwwwkmugovuacontrolukpublisharticleartidampcatid","mid.ru",
                     "noneimg", "solid", "start", "stylefont-s", "stylefloat", "classfield-item","cackle.me","container","dtp.kiev.ua",
                     "classfield", "classfield-itemsdiv", "field-label-hiddendiv", "hrefhttpwwwaddthiscombookmarkphpv","replyua.netпро",
                     "srcbmimgcomuaberlinstoragefinancexebfcbeadfdeccjpg","cackle_widget.push","document.createelement","polytics","loading",
                     "eff", "i","classfield-item", "classfield", "classfield-itemsdiv", "field-label-hiddendiv", "datatyp","i.lb.ua",
                     "propertyrdfslabel", "datatyp", "propertyrdfslabel", "skospreflabel", "typeofskosconcept","mc.src","erve.ua","www.pravda.com.ua",
                     "reldcsubjecta", "classfield-tag", "field-type-taxonomy-term-refer","document.createelement","mc.type","lb.ua",
                     "classimagecach", "classlink", "classrtejustifyspan", "classtranslation-link", "classtranslationru","goo.gl","newsru.co.il",
                     "clearfixdiv", "data-colorbox-gallerygallery-node--ytzaljghei","document.getelementbyid","javascript","mon.gov.ua",
                     "propertyrdfslabel", "skospreflabel","этом","это","які","від","datatyp","-tag","function","innerhtml","sevastopolnews.info",
                     "hrefhttpkorupciyacom", "дуже", "там", "так", "але","span", "width", "classleftimgimg", "stylecolor", "stylefont-famili",
                     "hspace", "vspace", "clearal","classback-block","tabletrtd", "valigntop","document.location.protocol","zakarpatpost.net",
                     "hrefhttpwwwaddthiscombookmarkphpv", "even", "как", "titl","document.getelementsbytagname","text","true","sport.ua",
                     "sea", "black", "hold", "one","stylemargin", "color", "outlin", "pad", "none","nbsp","widget.js","www.unian.net",
                     "centerspan", "size", "stylefont-s", "font-siz", "divfont","s.nextsibling","s.parentnode.insertbefore","www.ukrinform.ru",
                     "justifi", "center", "width", "height", "classfeed-descriptionp","window.cackle_widget","xcoal","politics","newsru.co.il",
                     "pimg", "wp-post-imag", "margin", "sizesmax-width","justifystrong","joinfo.ua","1news","journal","unn.com.ua","newsonline24",
                     "srchttpimageunncomuaoriginaljpg", "altновости", "centerimg","styletextalign","stylefontsize","justify","fontsize","padding",
                     "helvetica","laquoР","raquo","httpnovostimiracomnewshtml","hrefhttprkrinuauploadspostsmatigeroyinyajpg","news_180574",
                     "hrefhttpskeletinfoorg","pem","leaders","hstrong","development","religious","targetblankstrong","politico","news_180572",
                     "che","glucosio","person","primarily","hrefhttpskeletinfoorg","classmetanav","clearall","newsoboz","politika","news_180571",
                     "stylefontfamily","arial","fontfamily","outline","sansserif","textalign","border","inherit","left","pspan","naviny.by",         
                     "justifyspan","rgb","styleboxsizing","small","googleadsectionend","womenbox.net","arianespace","polityka","porfyrios",
                     "classfielditem","classfielditemsdiv","fieldlabelhiddendiv", "also", "article", "Article","cellpadding","finanso.net",
                     "download", "google", "figure","fig", "groups","Google", "however","high", "human", "levels","alt","feed","image","src","http",
                     "jpg", "larger", "may", "number","class","новости","gazeta.ua","rossii.html","zn.ua","cellspacing","portal",
                     "shown", "study", "studies", "this","img","using", "two", "the", "Scholar","pubmedncbi", "PubMedNCBI","p","photocharles",
                     "view", "View", "the", "biol","div","via", "image", "doi", "one", "classbackblock","dubinsky.pro","posted","news_180560",
                     "analysis","nbspap","photocharl","dharapak","pimg", "srcbmimgcomuaberlinstoragenewsxabddbdbajpg", "alignleft", "nbspnbspnbsp", "href",                      
                     "fieldnamebody","fieldtypetextwithsummary","title","datatype","fieldtypeimage","typeoffoafimage","www.globallookpress.com",               
                     "classcolorbox","fieldnamefieldimage","fieldtypetaxonomytermreference","rdfsseealso","relogimage","evenidfirstp",
                     "sizesmaxwidth","wppostimage","sizedecosingle","styledisplayblock","classattachmentdecosingle","hrefhttpspolitekanet",                                 
                     "httpspolitekanetwpcontentuploadsefebimagexjpeg","httpspolitekanetwpcontentuploadsgettyimageskopiyaxjpg","replyua.net.так",
                     "httpspolitekanetwpcontentuploadsunianxjpg","httpspolitekanetwpcontentuploadsgettyimagesxjpg","joomla","slavdelo.dn.ua",
                     "classfielditems","odd", "classfielditem","fieldtypetext","stylewidth","classimage","classimageattachteaser","imageattachnode",              
                     "medium","tahomaarialhelveticasansserif","imagethumbnail","classimagecache","pxa", "fieldfieldnewslead","fieldfieldyandexnews",
                     "srchttpinmediakitemscachedddddbbecbesjpg","srchttpsgoroddpuapicnewsnewsimagesmjpg","srchttpwwwkanzasuauploadpicresizejpg",
                     "ampraquo","hrefhttpelvisticomnode","hrefhttpwwwgazetamistoteualajntranslyatsiyaforumudetsentralizatsiyaosnovaformuvannyanovoyisystemyupravlinnyatamistsevogorozvytku",
                     "forklog","hidden","hrefhttpgiuauseridurlhttpsaffnewstutbyfeconomicsfhtml","lineheight","overflow","colorspan", "pxbbrspan","sizeb",
                     "srcbmimgcomuaacommonimgicstarsemptyvioletgif","altimg","titleСЂР","hrefhttpvideobigmirnetuser","srchttpbmimgcomuavideoimgsxjpg", "table",
                     "mediumspan","sansarialsansserifspan","langruruspan","classfooterinfosocialitemfollows","classfooterinfosocialitemiconspan",
                     "hrefhttpwwwpravdacomuarusnews", "classfbcommentscount","що","который","которые","также","таким","новости","несмотря","в","на","и","не",
                     "что","у","о","по","с","про","за","з","до","і","що","экс","об","этом","из","к","от","та","для","екс","це","его","а","как","politeka","он",
                     "від","його","новости","это","твій","года","суті","при","під","после","того","через","будет","так","липня","том","уже","більше","як","все",
                     "но","щодо","які","которые","то","2017","против","также","далее","новостей","він","своей","також","еще","перед","который","є","под","сути",
                     "твой","знай","михаил","со","году","року","я","видео","проти","сил","із","сейчас","чтобы","dneprcity.net","же","й","может","над","или",
                     "стало","было","може","тому","буде","те","был","быть","между","фото","112","який","ua","только","чем","является","ли","более","21",
                     "26.07.17","без","було","вже","где","зі","ще","19","2018","laquo","мы","raquo","вона","кто","ми","своїй","ст","яких","были","ему","их",
                     "наших","него","особо","очень","себе","щоб","де","ее","зараз","котором","сам","своем","теперь","цього","але","если","которая","себя",
                     "тем","эти","https","больше","був","бути","два","навіщо","нас","таки","тогда","replyua.net","будут","йому","між","можно","ним","новость",
                     "п","ч","чи","12","50","mc","должен","им","именно","источник","которых","меньше","стал","эту","буду","має","стоит","требует","этот","11",
                     "http","была","высокий","день","имеет","її","мог","несколько","них","она","этого","вони","всего","вся","когда","которым","одним","почти",
                     "разі","стала","була","всі","вы","даже","дал","дать","кого","которое","м","нет","ни","новину","оборони","один","поки","потому","свою",
                     "стали","таким","этой","яка","якому","яку","script","the","var","ей","новини","одно","понад","проте","серед","такий","чому","вот","дати","есть",
                     "без", "більш", "більше", "буде", "начебто", "би", "був", "була", "були", "було", "бути", "вам", "вас", "адже", "увесь", "уздовж", "раптом", "замість", 
                     "поза", "униз", "унизу", "усередині", "в", "навколо", "от", "втім", "усі", "завжди", "усього", "усіх", "усю", "ви", "де", "так", "давай", "давати", "навіть", 
                     "для", "до", "досить", "інший", "його", "йому", "її", "її", "їй", "якщо", "є", "ще", "же", "за", "за винятком", "тут", "з", "через","або", "їм", "мати", 
                     "іноді", "їх", "якось", "хто", "коли", "крім", "хто", "куди", "чи", "або", "між", "мене", "мені", "багато", "може", "моє", "мої", "мій", "ми", "на", "назавжди",
                     "над", "треба", "нарешті", "нас", "наш", "не", "його", "ні", "небудь", "ніколи", "їм", "їх", "нічого", "але", "ну", "про", "однак", "він", "вона", "вони", 
                     "воно", "знову", "від", "тому", "дуже", "перед", "по", "під", "після", "потім", "тому", "тому що", "майже", "при", "про", "раз", "хіба", "свою", "себе", 
                     "сказати", "з", "зовсім", "так", "також", "такі", "такий", "там", "ті", "тебе", "тем", "тепер", "те", "тоді", "того", "теж", "тієї", "тільки", "тому", "той", 
                     "отут", "ти", "уже", "хоч", "хоча", "чого", "чогось", "чий", "чому", "через", "що", "щось", "щоб", "ледве", "чиє", "чия", "ця", "ці", "це", "цю", "цього", 
                     "цьому", "цей","і","у","та","я","а","й","як","які","бо","із","який","тим","нам","б","всі","ж","яку","зі","яких","всіх","цим","1997","1991","1992","1998","2008",
                     "2009","2010","2011","2012","2013","2014","2015","2016","2017","рік","все","роком","році","нехай","хай","року","яка","них","ним","1996","то","новое время",
                     "эт", "de", "№", "»", "«", "г", "la", "us", "y", "во", "will", "р", "a", "images", "т", "g", "june", "los", "х", "е", "die", "н",
                     "of", "to", "in", "a", "and", "for", "is", "on", "that", "бы", "аби", "zu", "zwischen", "zwei", "zik", "z", "httpstmeasiaplus", "httpstmeasiaplus",
                     "znewslink", "zone", "zaxidnet", "young", "yet", "years", "yeahs", "yeah", "year", "ya", "yearold", "x", "wwwuafootballcom", "wwwrbcua",
                     "without", "withi", "werden", "whose", "win", "white", "whether", "well", "went", "w", "vs", "en", "el", "httpstmekorrespondentnet",
                     "хроникаинф", "тег", "facenews", "copyrights", "actualnews", "forex", "homefinanceua", "alyakа", "ctrl", "newagelabcom", "newsobozorg",
                     "salesnvua", "newsnvua", "vasyl", "kyrylych", "vasylkyrylych", "httprupostersru", "flash", "llc", "httpservermedisumcomuampphpidmp", "ubt",
                     "rnbhiphop", "сss", "php", "golosua", "runaway", "strokes", "vectra", "uaфутбол", "ukrmedia", "tribunacom", "tolonews", "thing",
                     "newsonline", "httpstelegrammemelitopolmv", "httpstmeodnews", "httpjpgazetaru", "cz", "ru", "ua", "afpgetty", "ha", "se", "getty", "con", "una",
                     "adblock", "usionlinecom", "ipnews", "previously", "odnewscom", "comua", "october", "planned",
                     "storinkacomua", "mignewscom", "running"     , "gazetazpua"     , "infolineua", "environment"   , "questions"    ,  
                     "actionscript" , "drumnbass" , "struck"      , "globe"          , "annual"    , "involved"      , "explained"    ,  
                     "sportua"      , "ruling"    , "joinfoua"    , "administrations", "november"  , "diario"        , "question"     ,  
                     "coalition"    , "uainfo"    , "organization", "aquarius"       , "знайua"    , "common"        , "investigation",  
                     "lionel"       , "period"    , "commission"  , "addition"       , "russias"   , "plan"          , "planes"       ,  
                     "foundation"   , "investment", "videorbcua"  , "operations"     , "began"     , "committee"     ,        
                     "migration"    , "position"  , "forum"       , "violence"       , "conditions", "голосua"       , "mignewscomua",   
                     "senior"       , "ios"       , "comment"     , "negotiations"   , "previous"  , "peoples"       , "rule"        ,   
                     "situation"    , "comments"  , "диалогua"    , "elections"      , "axios"     , "plans"         , "action"      ,   
                     "dtpkievua"    , "coming"    , "community"   , "played"         , "companies" , 
                     "players"      , "replyuanet", "bloomberg"   , "depoua"         , "gazetaua"  , "nations"       , "member"       ,  
                     "information"  , "run"       , "nation"      , "player"         , "opposition", "members"       , "region"       ,  
                     "decision"     , "newsone"   , "billion"     , "election"       , "trumps"    , "administration", "production"   ,  
                     "como"         , "sanctions" , "company"     , "guardian"       , "place"     , "immigration"   , "union"        ,  
                     "million"      , "play"      , "russian"     , "russia", "national",
                     "httpswwwfnewsruchampionshipaustriaqualshtml", "russianlanguage", "adequately", "httpswwwukrinformrurubricculturekalendarnavsugolovuiunahtml", "persuaded", "storinkacomuaэтот", "seksuaalivähemmistöjen", "gezuar", "httpsvpkname", "httpswwwnaturecomarticlesnature", "perustettu", "statedrug", "wwwvladrosscomua", "russianspeaking", "unorg", "httpscontwsgrif", "korruptionsprozess", "upmpnews", "httpstelegrammemelitopolmvпремьер", "grundsätzlich", "newscorp", "firstrun", "molbukuaвон", "httpsyoutubejqddbelmy", "paintbrush", "recomendarlo", "druha", "httpsyadiskdnntxkybg", "tmobilearenacom", "подивимосяhttpstcofvyihykqm", "ucranianorusa", "organisieren", "uaigotoworldcom", "vanguardia", "httpurainformcomrusocietyvukrainevnekotorykhoblastjakhobjavilishtormovoepreduprezhdenie", 
                     "rearguards", "httpsnewstutbysocietyhtml", "depositphotoscom", "sledcom", "natoannäherung", "httpstcojcovkflp", "rudy", "pictwittercomobixxhyei", "attackhttpstcoanfzjja", "eruptions", "httpsitcuanewskabminrazreshilispolzovatvmestotraditsionnyihkassovyihapparatovpkplanshetyiismartfonyipokatolkovramkahpilotnogoproekta", "composición", "httpurainformcomrueconomicsukrainavybilasvlideryproizvoditelejmolokavvostochnojevrope", "digitaltrendscom", 
                     "fbrugaagskayakonferentsiyaustanovilanormyivedeniyavoynyi", "httpallcrimeanet", "osvitanovacomua", "mysuru", "ladailynews", "httpsplusgooglecomhromadsketvuтелегр", "igatecomua", "forums", "httpsantikorcomuaarticlesizrovenskojoblastipytalisjvyveztihenshchinvseksualjnoerabstvo", "complicit", "newsterkey", "onlineuaclub", "httpsantikorcomuaarticlesukrainapoterjaetazovskoemoresdelanogromkoezajavlenie", "httpsshowdreamorg", "consormfagovuaзазначим", "natogeorgia", "instagramcomizabelgoulart", "facebookcomvisitkherson", "httpstcoiptutfmcf", "djua", "disorganized", 
                     "incommunicado", "perus", "macrumors", "infraestructura", "httpsinsideclimatenewsorgnewsarcticpermafrostmeltingmethaneemissionsgeologicsourcesstudy", "httpscontwskonorsте", "httpscountercurrentsorgadangerouszerosumgamedonaldtrumpvstheplanet", "bguslivejournalcom", "httpfinfrontruhuaweiistopsponsorofaustralianpoliticians", "httpnaspravdiinfomirpyatsamyhneobychnyhdomov", "httpsworksbepresscomjuliebrighamgrette", "stadtzentrum", "btvtnarodru", "httpedinstvennayaua", "individualidades", "ixbtcom", "russe", "tabloidinformatornews", "bankrun", "facebookcomgabrielwikstrom", "httpsmasterpluscouagtahodatchikidatchiki", "struve", "httpsteminutuapodiivtsentrimistapobiliinozemnihstudentivperehozhinedopomoglihtml", "jaguares", "qualities", "rudd", "rupees", "cimiccomua", "juttua", "obscurus", "quadrovpn", "httpnewscomuaavstriyapriznalatretijpol", "kushvsporteru", "httppolitikymnetobshestvo", "neboleycomua", "httpwwwcuavorgdvhtm", "httpurainformcomrusocietykgodunorvegijamozhetperejtinaelektricheskujuaviatsiju", "httpseadailycomrunews", 
                     "lowquality", "trurmps", "zaderijru", "commanders", "wwwyoutubecomwatchvgredczrkke", "martransgovua", "pictwittercomlkjubkak", "караулhttpstwittercomkrimrtstatus", "hervorgehoben", "paraguay", "accentuated", "httpswwwncdcnoaagovabruptclimatechangeheinrichanddansgaardeoeschgerevents", "httpstwittercomhubkukrainestatus", "httpsokoplanetsupolitik", "sorgten", "organisms", "newcomer", "парусаhttpswwwyoutubecomwatch", "httparhemskru", "verursacht", "httpnaspravdiinfonovostisamyeudivitelnyekonstituciimira", "lifehackercom", "httpmozgovuadostupniliki", "httpwwwanaslavruforumviewtopicphpt", "twittercomscmpnews", "odessanetua", "newsfinance", "nbacom", "источникhttpsknpartnerscomua", "wwwcosmocomua", "фотоinstagramcomvitalinka", "madrugada", "habitualmente", "papillomavirus", "zmickua", "ділянокhttpswwwkolonanetfeed", "mignews", "httpkivertsirayoninuanewsdidichicholovikzatiazhkitilesnimozhenepotrapitizagrati", "reconstructing", "infomstudionetua", "pictwittercomoryegmilr", "widerspruch", "marijuana", "trupin", "httpstcolozgeenq", "httpstcozumowurk", "rushes", "estructuras", "httpstsargradtvarticlesa", "complied", "httpkhersonnetua", "advocatsergiygulacomдержавн", "bevölkerungsreichen", "petersantenellocom", "comingout", "httpsnewsmailrusociety", "regierungschefs", "zpdsnsgovua", "httpspdwcompxrk", "depouaя", "httpswwwpopmechruscience", "sovietruled", "lentaruofficial", "nonrussian", "httpurainformcomrusocietyvukraineskazhdymdnemostaetsjavsemenshebolnits", "perustelee", "httpsyoutubexsztumr", 
                     "httpstmekorrespondentnetджерел", "lieferungen", "nouakchott", "httpsriarueconomy", "chmrgovua", "acronru", "instagramcomalinagrosu", "reutersammanbeirut", "rustarstv", "facebookcomrodionshovkoshytnyi", "httpstcoybvvn", "httpswwwprometejinfoblogdiskussiyamymozhemostanovitvoennuyumashinu", "httpurainformcomrupoliticssshanamerenyumenshitkolichestvovojskvgermanii", "httprgrunacbezopasnostsitedokhtml", "wwwukrinform", "constructoras", "erleichterungen", "httpisportuabasketballworldsbornajaukrainykvalificirovalasnachempionatevropypobasketboluh", "russischstämmigen", "intelectual", "wwwpravmirvelikayaneizvestnayaiobolgannayakstoletiyupervoymirovoyvoynyi", "httprusklineruoppiyun", "bocom", "quadhd", "kremlinru", "frutos", "httptwittercomdwukrainian", "quantity", "httpsyoutubeviwtnluqkmy", "httpscontwskonorsмарин", "scrumhalf", "quashing", "comunicaciones", "biolcomua", "instagramcomhotcelebritiesnews", "russischschweizerischen", "httpsyoutubegdxqfdqjdia", "neboleycomuaона", "haettua", "newsnnспециалист", "womanhitru", "airup", "httpcredopro", "putintrumptreffen", "trusteeship", "reolyuanet", "vorrunde", "commercials", "twittercomjnrsaks", "aufklärungsdaten", "pictwittercomhfblmcsboq", "faktyictvua", "peruu", "compelled", "cgmonitorgmailcom", "neboleycomuaэкзосом", "ua", "instagramcomparishilton", "интернетua", "radarboxcom", "httpsokrubylinaavttopic", "dilovacomua", "httpspogodauniannetnewsukrgidrometcentrobnarodovalprognozpogodynaiyulhtml", "zeebrugge", "httpstcoeflfe", "povnijabsoludgmailcom", 
                     "httpscreditparkcomua", "verbesserung", "httpsgithubcomnakasendo", "httpstcowhxbx", "datenschutzerklärung", "httpavtosaleua", "youtubecomrussian", "pacsafecom", "acquainted", "pictwittercomqzizvsdfl", "dovzhenkoscriptsgmailcom", "maksimiljichyandexru", "mfagovua", "jurisprudencia", "rutsaert", "pmpplistru", "instructs", "luanavjollca", "capitalua", "pictwittercomgdkwajce", "httpsvkcommartiniszph", "httpswwwannualreviewsorgdoiabsannurevearth", "organisator", "russiagateermittlungen", "wsjcom", "recruiters", "quagmire", "httpdwcomukrainian", "httpscontwskonorsтеб", "httpurainformcomrueconomicsvverkhovnojradestartovalkapitalnyjremont", "menschenrechtsorganisationen", "hafenrundfahrt", "httpsantikorcomuaarticleschinovnikikupilinovyhplavsredstv", "wwwfifacomworldcup", "pictwittercomnzfmraw", "englishlanguage", "httpwwwfacebookcomdialogsendappidredirecturihttpsaffpdwcomfpfbcqfmacadrufacebookbmessengerbwebsharinglinkhttpsaffpdwcomfpfbcqfmacadrufacebookbmessengerbwebsharingdisplaypopup", "realvincom", "rudely", "coachtruck", "httpscontwskonorsскор", "httpstsargradtvarticlesktovinovatchtonashihzhenshhinuvodjatinostrancy", "comercializar", "regierungstruppen", "forbesru", "russlandfans", "quadstick", "osua", "boredpandacom", "httpexpresuagfximagecachethnewsmainjpeg", "combustion", "vorgenommen", "pictwittercomuzmcywf", "urus", "facebookcomevents", "наркотикамиstylerrbcua", "comentó", "unqualified", "orgánico", "wwwstoletieterritoriyaistoriiandrejkhvalinetoepohalnojebyloputeshestvijehtm", 
                     "httpswwwprometejinfoblog", "informatorua", "nafrontiua", "indianexpresscom", "громадськогоhttpshromadskeuaгромадськ", "twittercomatletistatus", "verurteilt", "preventepidemicsorg", "schiffsgruppen", "httpwwwstenaeeblogeston", "httpscasinovulcangoldcomtable", "httpsmfacebookcomstoryphpstoryfbididуправлен", "httpwwwranlifecom", "zumapresscom", "httpoblvesticomua", "rumores", "comparación", "compressor", "сшаageofcompinfo", "eparhiyaodua", "httpscontwskonorsлед", "httpsgooglkzsl", "bisexual", "comer", "evaluación", "natoinfrastruktur", "cruz", "httpwwwozarincinarodrudownloaddzhurynbpdf", "httpswwwncbinlmnihgovpubmed", "httpswwwgazetaruarmynewsshtml", "commentaries", "httpsordoiurisplpublicplikidokumentyraportprzemocoipdf", "truckdriving", "pictwittercomnvpzlxqep", "wwwrbcrupoliticsaffadf", "subcommittee", "httpwwwcollegekulturiuzua", "httpfinfrontrurussiaandopecholdidealoilprice", "meridianinua", "golosuaкарикатурист", "asua", "zabriskiru", "httpstwittercommikhailsha", "pictwittercomlijqxejzr", "httpskirilllivejournalco", "commonality", "drummers", "httpsmmaprnewswirecommediauniversalmusiclatinentertainmentjbalvinspotifyjpg", "wwwhostingkartinokcom", "turusgas", "uncommon", "veränderung", "nahrungsmittel", "uaкрим", "hurum", "igualó", "baltnews", "pictwittercomrbfpxxz", "uninterruptedly", "altruistic", "arantepacua", "forge", "erunru", "comparativa", "instagramcomchabandenis", "minggeorge", "httpsmoslentarucitymoskv", "rumtid", "knliferu", "газетойru", "arudavkabeitcomua", "gazetauaмы", 
                     "httpurainformcomrusocietyedashiranaobvinilivkrazhepopuljarnojkompozitsii", "jobsbuorg", "httpswwwgazetarutechaihealthshtml", "earthquake", "слухиstylerrbcua", "httpscontwskonorsкак", "contentampampampquothttpvideomagnetkievuapspthumbnailentryidnlqlmcuversionacvampampampquotampampampampampampampampampampampampampampampampgtampampampampampampampampampampampampampampampampltspanampampampampampampampampampampampampampampampampgt", "httpscontwskonorsна", "httpsruxpertruпенсиивросс", "uaукраїнськ", "construida", "httpswwwukrinformrurubricsportsvolejbolukrainskieklubyuznalisopernikovvevrokubkahhtml", "vorgaben", "tvgidua", "punctuation", "organophosphate", "quantifiable", "uadepositphotoscom", "newsmstudionetuaemail", "httpurainformcomrusocietyvmoskvegorodskievlastizapretilimeksikanskimfanamorganizovatparadko", "hinnanmääräytymisperusteet", "dariknewsbg", "pictwittercomppyqzosjon", "wwwproza", "rubro", "acompañe", "combating", "mkru", "httpwwwvsemirnyjbankorgrueventsdevelopingthedigitaleconomyinrussiainternationalseminar", "pictwittercommswgjbxqx", "unabhängigkeitserklärung", "ilmoitettua", "rockmusicru", "burundi", "httpstsargradtvarticleso", "antirussian", "hypercomments", "comercializadoras", "prianru", "httpsyadiskdpzxcyhybgwav", "konstruktivem", "dualcore", "доступуhttpswwwhomoseksualizmeduplwiecejpublicystykanietolerancja", "patrullan", "pictwittercomszbojdy", "sääntöperusteista", "tumblrcom", "newstj", "rudis", "facenewsчита", "mduinua", "policednua", "rivnepostrvua", "soccernewsru", 
                     "cloudcomputing", "megafonodua", "httptcotuwdhx", "pictwittercombgltfoqdzje", "verkehrtherumbikini", "crusade", "httpwwwistpravdacomuaarticleseafe", "noruegas", "httptassruekonomika", "interruptions", "russiansoviet", "klimaschutzvereinbarung", "httpsdonkatarlivejournalcomhtml", "wwwhistmsurueretextforeignbosporushtm", "neskuchnonewscom", "facebookcomoliashko", "httpstcotnqthmi", "lkfrbkru", "ruskeala", "pictwittercomaitebeox", "avianewscom", "alternatehistorycom", "ehdokaskeskustelua", "httpssputnikgeorgiarupoliticspervoezayavleniebaxtadzevkachestvepremerministrageorgiahtml", "alnuaima", "veränderungen", "excommunication", "interua", "quasifederal", "änderungen", "internewsislamabad", "pictwittercomssyipmfsf", "planetabelarusby", "rumour", "hrucueduua", "huatai", "biocombustibles", "qualitatively", "forging", "grube", "gruenders", "communism", "znajuaякщо", "commemorative", "ahuacamolli", "verbesserungen", "facebookcomcrimeansolidarity", "httpswwwyoutubecomusers", "годыwwwtheplaceru", "incompatible", "ejruanoteid", "accompanying", "uatribunacom", "complicating", "httpsnarzurru", "verborgenen", "httpwwwfbuuanewszbirnaukranihkvalifikuvalasyanachempionatvropi", "httpsrusputniknewseeestoniannewsposolusaestoniamelvilleotstavkatrumphtml", "comúnmente", "uspehrussia", "contactnchaincom", "igualdad", "uainfoorg", "newsdnua", "uamotors", "buvrtysagovua", "russinnen", "spacecom", "рeoрlesru", "erklärungen", "restructuring", "wwwgloballookpresscomотмет", "abhirup", "httpswwwfacebookcomulanasuprunposts", 
                     "radomyshlblogspotcom", "aacomtr", "httpsgreycrocolivejournal", "httpsnewdaykhersonuakahovskazorjapovinnazvilnitiprimishhennja", "httpswwwlvivhiphopallstarcom", "ageofcompinfoов", "uap", "pictwittercommfoohyqzen", "comprometido", "ruskinoru", "comunicación", "httpsdeclarationscomuadeclarationnacpefdeabbbd", "muangthong", "pictwittercomygrsmbor", "vnminutua", "druschinin", "youtubehttpswwwyoutubecomwatchvnnigragkactionshare", "httpscontwskonorsсчёт", "visyschengencomua", "сторінкиuainfo", "httpskorrespondentnetworldvytalyyprydumalyshtrafdliaturystov", "dislozierung", "facebookcomkharkivdsbt", "compara", "drugmakers", "httpscontwskonorsоб", "evacuations", "httpklitschkobrotherscomnovostiukrainecsirenkozavoevalpervyititulnaprofessionalnomringehtml", "httpsienilovabibliowikiru", "httpsxtrueinfoklyu", "facebookcomodalug", "httpspublizistrublogsutmsourcepolitobzornet", "juarez", "allurecom", "truckload", "httpsgetzaimcomua", "complexed", "commotion", "truces", "pictwittercomlznkxgdxyg", "cuauhtmoc", "unscrupulous", "httpbitlyorganfest", "httpwwwelectoratinfoblog", "komandaonlinecom", "akketcom", "morgen", "httpwwwdsnewsuapoliticssegodnyadenpamyatinazariyayaremchuka", "georgische", "rgru", "ruporinfo", "gazetauaза", "taoyuan", "httpswwwprozarucgibinloginpagepl", "verbraucherorganisation", "crucible", "foxnews", "httpswwwsvobodaahtml", "httpswwwsmithsonianmagcomscience", "httpswangeliylivejournalc", "patriotyorgчутк", "httpscontwskonorsлюбов", "quórum", "pictwittercomymqionlorf", "httpscontwskonorsоксти", 
                     "wwwdynaconcontentarticles", "oppositionsgruppen", "agroreviewcom", "medaboutmeruв", "pictwittercomdsacazem", "comenzado", "regierungszeitung", "perusteita", "httpberegrusrup", "pictwittercomqnlsvkln", "compuesto", "ternopilmnsgovua", "dtpkievuaозверевш", "uaдонбас", "httpsvkontakterusharephpurlhttpsaffpdwcomfpfbcqfmacadruvkontaktesharingtitledadbddbdfdbddbdbddbddbdfdbedbfddbedbdbddbdbbdbdbdbdbadbbdeddbdbddbdbddadadddbedbdbbdbddbdbddbdfdbfdbedbdbdbdbdbdddbdbc", "khrushcheva", "uvzru", "lodagovuaфункціональн", "compensarlo", "pictwittercomtwvedkfkj", "fclvivcomua", "httpscontwskonorsмамон", "twittercomrealuran", "besorgtheit", "рожденияstylerrbcua", "comando", "httpsyoutubetwlhjqruclu", "geonamesorgmapsgooglehtml", "compaq", "compel", "партнерівpictwittercomgipoounom", "trumpeting", "httpsnewsmailrufrommail", "hinewsru", "httpswwwtwittercomgacmotor", "pictwittercomynygkhhk", "compases", "neupositionierung", "tvilru", "chorus", "httpscontwskonorsчад", "besplatkaua", "crushes", "httpwwwodnoklassnikirudkstcmdaddsharestsstsurlhttpsaffpdwcomfpfbnzfmacadruodnoklassnikisharing", "defensenewscom", "httpkolokolrussiaruideologiyakakoyvergermansterligovhcqyzptuwq", "пьетеstylerrbcua", "commentates", "comportamiento", "uncompetitive", "truedepth", "yuriyshogenovinfortrendcom", "httpscontwskonorsодно", "paruby", "httpswwwmunichrecomtopicsonlineentopicsgeooverviewnaturalcatastrophe", "httpstwittercomcrimeauastatusскрин", "httpsvarjagsulivejourn", "newshub", "httpcominforg", 
                     "httpurainformcomrusocietymessiotkazalsjazhitvoteljarjadomsmuralomronaldufoto", "httpscontwskonorsмы", "httpswwwyoutubecomwatchvouwdoovztfeatureyoutube", "wwwomen", "euromagru", "militarycom", "organise", "recomprase", "lentaruв", "brust", "barullo", "youtubehttpswwwyoutubecomwatchvirjluwsqoactionshare", "httpfriendв", "wwwxxlrukadetiruskorpushtmvasiljev", "fainaideacom", "combrinck", "httpwwwinsorgorg", "storinkacomuaдля", "wwwgloballookpresscomони", "wwwrmkeeru", "uagoloscomкартинк", "httpscontwskonorsнеловк", "tmzcom", "httpscontwskonorsнемн", "httpstcoukgaehzdp", "httpscontwskonorsнесистемн", "pictwittercomwulcojegu", "httpscontwskonorsтут", "burundis", "commanded", "championcomua", "httpswwwnasagovsitesdefaultfilesthumbnailsimageimagefiguresjpg", "kohtelua", "wwwrmkee", "offguard", "cualquiera", "httpscontwskonorsэх", "httpswwwchangeorgpпр�", "httpstwittercomkrimrtstatusфот", "idominicanacom", "organelle", "actualiza", 
                     "appleinsiderru", "breitbartcomdownrange", "informuainfo", "httpstelegrammeshareurlurlhttpsaffpdwcomfpfbcqfmacadrutelegramsharingtextdadbddbdfdbddbdbddbddbdfdbedbfddbedbdbddbdbbdbdbdbdbadbbdeddbdbddbdbddbedbdbbdbddbdbddbdfdbfdbedbdbdbdbdbdddbdbc", "pictwittercomiwfgwtxzg", "ghallcomua", "httpscontwskonorsсентябр", "commentating", "arutz", "typisierung", "partrunaway", "gpgovua", "threequarters", "bolschewisierung", "protruding", "completó", "httpmaxparkcomcommunitycontent", "smithsoniancom", "ruin", 
                     "очковбразилияшвейцариясербиякостарикаimghttpsscontentarnxxfbcdnnetvtnjpgnccatohbfadecffdcaoebbbeeimgзагрузк", "httpsphysorgnewswintercoldextremeslinkedhighaltitudehtml", "grudgingly", "comprar", "noncompliant", "uamotorsportcom", "squashpumpkin", "milleruibo", "graziamagazineru", "ruвертуха", "construyen", "httpparanormalnewsrunews", "newsmiass", "casually", "khrushchevamoscow", "kmugovuaтам", "mignewscomuaесли", "mirgorodkurortua", "antiaufklärung", "complicación", "httpsyoutubevitapwtbo", "zbirnacom", 
                     "адресуnbspshtdmbsoccereventscom", "tvuaфот", "календареаифua", "antikorruptionsstandards", "pictwittercombqxhwvdqk", "pictwittercomgrqoiyo", "compuesta", "instrucción", "compliment", "httpsyoutubehdexmewjpek", "httpswwwukrinformrurubricworldcerezdvenedelimakedoniipredlozatnacatperegovoryovstupleniivnatohtml", "btuorguaукраинск", "wwwdwcomplprzemocwobecdzieciporacbcajccedanezrfna", "httpswwwsegodnyauaimgarticletnjpg", "ruega", "absicherung", 
                     "httpwwwbbccomearthstoryinsiberiathereisahugecrateranditisgettingbigger", "wwwcryptonomicsio", "alabanzaru", "vfestru", "accomplishment", "theguardiancom", "источникizmnews", "httpskrasnodarruspiperu", "instrumentality", "forgo", "httpportnewsru", "httpnaspravdiinfonovostichastukraincevmogutlishitpensiy", "knopfdruck", "httponlinelibrarywileycomdoipaabstract", "squares", "httpstsnuadenvistoriidchervnyavistoriyihtml", "instagramcompasslovesky", "vestiuanet", 
                     "wwwkfssrucontentvostochnoeputeshestviecesarevichanikolayaaleksandrovichach", "newsnight", "httpscolonelcassadlivejour", "httpscontwsslavikapple", "instructors", "complementary", "газетыru", "somosaguas", "replyua", "coaequales", "httpstcojifhyec", "httpurainformcomrusocietyvavstriiofitsialnorazreshiliregistrirovattretijpol", "väestönkasvualuetta", "weißrusslands", "anual", "httpswwwpravdacomuarusnews", "rubiks", "instagramcomtribunedit", "comprarla", "gruppenspiel", 
                     "httpsaftershocknewsqnode", "pictwittercomzmyxpps", "communique", "httpstcolbgvzubz", "httpszaimonlinerucom", "httpstcojnpknaf", "httpswwwtedcomtalkspeterwardonmassextinctionstranscript", "organizationally", "httpstmevestichat", "wwwlexikonderwehrmachtdewaffenminenhtml", "httpspeaceinukrainelivejournalcomhtml", "httpsokrytoenetnlozh", "httpswwwukrinformrurubricculturevkarlovyhvarahotkryvaetsakinofestivalpokazutitriukrainskihfilmahtml", "competent", "httpurainformcomrupoliticsvlastiafganistanavnovobjavilivojnutalibam", 
                     "bielorrusia", "evaluating", "httpswwwukrinformrurubricsocietydvoesutokozidaniacastturistovuzevernulasstunisavukrainuhtml", "httpsafeinetcom", "vstuposvitaua", "mutuality", "httpsuranewsnews", "compellence", "будущемageofcompinfo", "intrusion", "httpwwwistpravdacomuacolumns", "pictwittercomzhuyxqgzx", "httpsrutsnuavideovideonovinimesyacbezvodyzhivutlyudivseledarevkahersonskoyoblastihtml", "commonplace", "organismos", "pictwittercomswizqoqbn", "gruesas", "httpdzerkalozakarpattyacom", "pictwittercomehrnfwizar", 
                     "rupee", "recommit", "comparecencia", "fruto", "koordinierung", "pictwittercomekakul", "urupor", "wwwinfortrendcom", "httpswwwbritannicacomscienceyoungerdryasclimateinterval", "russlandwesten", "druri", "pictwittercomfdoowfqjo", "httpxsportuafootballsnewsfrantsiyavkrasivommatchevybilaargentinuizchempionatamira", "rudelfilt", "sääntöperusteinen", "antirusslandagitation", "courtgovua", "awrhawkinsbreitbartcom", "guatemalan", "httpsuamirvgruziiperenesliekzamenyvvuzyizzagradusnoyzharyhtml", 
                     "вступосвітаua", "httpsmmaprnewswirecommediagacjpg", "httpswwwsciencedailycomreleaseshtm", "strut", "homosexual", "continua", "russianoccupation", "kharkovdozorua", "unusually", "commonlyowned", "organics", "konstruktive", "pictwittercomzakdjhgm", "httpgordonuacomnewslocalnewsvukraineizzanepogodyobestochenynaselennyhpunktahtml", "truthout", "runday", "httpamenrarup", "escuadra", "httpwwwfacebookcomsharersharerphpuhttpsaffpdwcomfpfbcqfmacadrufacebooksharing", "httpsumusicboxcomsyaopaibwxhbzkeyktq", 
                     "unguarded", "verschlechterung", "httpsnarodnapravdauavavstriyivyznalytretyustat", "compositions", "neuartiger", "drunkards", "ritualen", "cruceta", "completarán", "httpscontwskonorsчтот", "kruse", "abrufen", "httpwwwfacebookcomsharersharerphpuhttpsaffpdwcomfpfbnzfmacadrufacebooksharing", "vdvmilgovua", "situada", "agroinvestru", "httpsiskrakungurruall", "moruinho", "httptassrupolitika", "pictwittercomwcdmrvor", "httpscrimeauawordpresscom", "httpedemgardencomua", "httpstheiconuazhenshchinamodezhdafutbolkiimayki", "denuklearisierung", "truths", "ordcomgmailcom", "luana", "httpswwwyoutubecomwatchvyryxcyicyg", "bookingcom",
                     "httpswwwsciencedirectcomsciencearticlepiisx", "obozrevatelcomв", "pictwittercomleuopwlks", "brgcom", "comedor", "httpsregnumrunews", "httpceladorucatalogblackfate", "foodtrucks", "pictwittercomxutfbqz", "betainuaтакж", "gacmotorcom", "exceptuando", "bykvucom", "газетаru", "httpscontwskonorsвольн", "perusteellista", "dua", "konstruktsioonide", "iledebeauteru", "lauantaiiltana", "pictwittercomugmdnsoi", "satoru", "graduates", "uac", "organisatoren", "httpskoshekruprodolzhitel", 
                     "thyssenenkrupp", "pictwittercomaesjzkew", "comrades", "organises", "tricom", "httpswwwinstagramcomlvivhiphopallstar", "decommissioned", "httpswwwua", "quantas", "grundstock", "httpomrgovua", "gazetauaпорошенк", "mossudmedlivejournalcom", "youtubecomnação", "vestuarios", "voronzinuaновост", "autoua", "wwwvisitkhersongovua", "quadrant", "newsonf", "forgetting", "newstesru", "httpwwwnewsweekplpolskailuhomoseksualistowwpolscechcewziacslubartykulyhtml", "travelaskru", "gsmarenacom", "httpurainformcomrusocietysshanamerenyumenshitkolichestvovojskvgermanii", "pictwittercommlmwrwz", "pictwittercomvdjjqiwade", "httpspdwcompvnox", "httpsdropmefilescomjiunq", "httpsvkcompltrk", "compromised", "ruinous", "continuado", "sylru", "individuality", "httpswwwgfdlnoaagovbibliographyrelatedfilestdpdf", "httpwwwuniversalmusiccom", "cutliferu", "autodestrucción", "ruß", "armadaboardcom", "wwwxxlkadetiruskorpushtm", "deeskalationsvereinbarung", "quantitatively", "httpnewtopruorgpermanent", "httpsmmaprnewswirecommediagssuvjpg", "wwwshevafestcomреклам", "instagramcomkyivmy", "macquarie", "brush", "vorsklacomua", "politroscom", "rubley", "carolinegarciaumusiccom", "httpsgazetauaarticleseconomicsvidzavtramagazinireshtunevidavatimutdribnimikopijkaminovipravilazaokruglennya", "httpproxyinsorgorg", "rivnistinua", "prudently", "httpswwwfacebookcomcrimeansolidarityposts", "pictwittercomhcjxtghwy", "httpmatrasyoukievuabespruzhinnyematrasy", "httpsvpressarueconomyarticle", "instagramcomgiselecoria", 
                     "evacuating", "ecuador", "ruedas", "httpcccpkpssnarodrubpk", "httpvmestezporg", "httpsheadinsidernetcelebnyhsvojstvrisovojvodyutmcampaignutmsourcesendpulseutmmediumpush", "httpsfacebookcompltrkru", "trumploving", "faktyuaэдвардс", "comienza", "arum", "undergraduate", "kahharlivejournalcom", "freepikcom", "brushing", "comparisons", "hromadskeua", "governorgeneral", "alwaysbusymamacom", "neboleycomuaкак", "httpbooksonlinecomuaview", "ruining", "fluctuationsxv", "comunicó", "httpswwwfacebookcomkharkivdsbtposts", "karpatnewsinua", "wwwmedicinaportalcom", "vokrugsvetauaна", "hauptberuflich", "leibnizzentrum", "голоcua", "fcdynamokievua", "comparten", "corruptionwhile", "wwwichumanrightsorg", "uanimals", "httpxsportuaboxingsnewssirenkounichtozhilsopernikavpervomzheraundeidobylpervyytitulvkarere", "nalogru", "httpswebwhatsappcomsendtexthttpsaffpdwcomfpfbcqfmacadruwhatsappbwebsharingdadbddbdfdbddbdbddbddbdfdbedbfddbedbdbddbdbbdbdbdbdbadbbdeddbdbddbdbddadadddbedbdbbdbddbdbddbdfdbfdbedbdbdbdbdbdddbdbc", "httpszolochivnet", "httpdhozrudbaddbdddcdfdbdddbadbdbdbeddbdbddbddbdbddbddbddbcdbddbdbcdbddbdbdbbdbdbdbdbdbdbddbdbcdbedbbdbedbdbdb", "comienzos", "russianshowbizinfo", "httpswwwukrinformrurubricsocietyiunapamatnyedatyhtml", "trcredsquare", "httpswwwstoretheraptorscomraptorsdemarderozanjersey", "httprusklinerunewsrlwupalcavsemirnogobankaohvatilirossiyu", "facebookcomgroupsgovarta", "infrastructures", "capitalgazettecom", "ineffectual", "httpswwwtruthdigcomartic", "httpstcoshnryoxh", 
                     "halua", "mariupolnews", "народаhttpstwittercomcrimeauastatus", "dämonisierung", "fromua", "borderrussian", "pictwittercomayzsgoao", "sectordepoua", "instrumental", "httpswwwccncomnewsflashbitcoin", "fomainua", "аgronews", "erklärung", "familiesbelongtogetherorg", "httpglobalwarmingberrensnlglobalwarminghtm", "httpscontwskonorsакм", "httpasninuauanewsnewsafganistanobjavilozaversheniiperemirijastalihtml", "vkcomgomeldetka", "httpsnnruspiperu", "pictwittercombbdtmett", "commodore", "httplibrupolitologgenontxtwithbigpictureshtml", "forgiving", "vorgeben", "httpexpertrusu", "vorsorglich", "newsрозвідслужб", "rubbished", "meituan", "veracruz", "httpscontwskonorsвесенняя", "perpetuate", "kinoafishaua", "httpsdonkatarlivejourn", "httpsderzhavasvetawebnoderu", "obozrevatelcomтак", "hilkevichru", "ukrainianvoanews", "httpurainformcomrupoliticsvirlandiipojavitsjaukrainskoeposolstvo", "httpwwwukrainefootballnetufbetvyigrayfutbolkusbornoyukrainyhtml", "legionmediaru", "httpsdclarencelivejournalcomhtml", "crushing", "wwweurointegrationcomua", "quarryman", "pictwittercomwkjwlwb", "cantorum", "httpmatrasyoukievua", "complacency", "httpstwittercomintenttweetsourcewebclienttexthttpsaffpdwcomfpfbnzfmacadrutwittersharingdddbfdbdbdddbadbdfdddfdeddbfdbddbbdbdbdbdbdbdbdddbdbdbdaddbdbdbdbdbdbcdbddbedbcdbcdbeddb", "httpufokulichkicomanomal", "icowatchlistcom", "httpwwwodnoklassnikirudkstcmdaddsharestsstsurlhttpsaffpdwcomfpfbcqfmacadruodnoklassnikisharing", "complies", "httpspsmagcomnewssuffocatingtheocean", 
                     "ezinforesursgovua", "httpdynamokievuablogchempionatmirasubektivnyiezametkisilaopredelyaetsyaslabostyu", "kontaktgruppe", "httpsienilovaru", "newsletter", "pictwittercomsankzsgfe", "guarantors", "drvua", "newsallcrimea", "httpswebwhatsappcomsendtexthttpsaffpdwcomfpfbnzfmacadruwhatsappbwebsharingdddbfdbdbdddbadbdfdddfdeddbfdbddbbdbdbdbdbdbdbdddbdbdbdaddbdbdbdbdbdbcdbddbedbcdbcdbeddb", "rubrykacom", "interrupted", "pictwittercomoxfltlo", "wwwukridcom", "microorganisms", "comenzar", "wwwcapitalua", "hintergrund", "httpswwwcapitaluarunewskitaysnizhaetposhlinynaavtomobilizapchastiinekotoryepotrebitelskietovaryixzzjwcjkh", "denguevirus", "httpwwwcraarcgccatxndvdlsfqtxrtsenghtml", "trumpet", "vanuatu", "brdua", "decadeshttpstcofomgqzyowpictwittercomxhfmklsjn", "httpscontwskonorsгладиаторы", "comunistas", "httpsmasteroklivejournalcomhtml", "politicocom", "korg", "httpsinosmirueconomic", "clevelandcom", "принциповhttprentvblogсвятосла", "moscowliveru", "xplanetcom", "suave", "homoseksualne", "coindeskcom", "facebookcomfcdynamoua", "httpwwwpeterburgrunewspeterburzhenkanamerenaotkazatsyaotpensiichtobyostavlyatdengisebe", "tantrums", "tereninua", "httpswwwunianuatourismnewsnachernigivshchinirozpochavsyakinofestivalpamyatirezhiserakanterahtml", "trukhanov", "httpkriminalukrainecomua", "httpsinstagramcom", "marcacom", "httpstcoetyrecksg", "reutersjoshua", "rum", "baruch", "onlinedetoxcom", "httpswwwfacebookcomgroupsmakarlife", "newsmaker", "uraldemru", 
                     "httpswwwuapolitykainformatsiinyivechirekskliuzyvneinterviuzpavlomrozenkomtransliatsiiahtml", "httpworldcrisisrucrisis", "httpstelegrammeshareurlurlhttpsaffpdwcomfpfbnzfmacadrutelegramsharingtextdddbfdbdbdddbadbdfdddfdeddbfdbddbbdbdbdbdbdbdbdddbdbdbdaddbdbdbdbdbdbcdbddbedbcdbcdbeddb", "httpwwwuhlibrufilosofijakrizissovremennogomirapphpmetkadoc", "httpstcohbyusbci", "httpurainformcomrueconomicsmeksikaikanadadogovorilisokruzhitsshaekonomicheskineobosnovannymi", "muassa", "httpvodokanalckua", "ruan", "compostela", "accommodation", "competente", "httpsmasterpluscouagsupportydlyastiralnyh", "decomposition", "httpsogrusociety", "httpswwwreuterscomarticleuseuropeweatheritalyfreezeengulfseuroperareromesnowdisruptsflightsiduskcngakl", "guardarla", "democratrun", "dualclass", "httprostecrunewsvertolet", "miscommunication", "httpsriafanrudni", "httpsstranniksenyalivejour", "pictwittercombfvdtcn", "mantsurovlivejournalcom", "днепропетровщиныbegdpua", "virus", "asxcom", "httpstvuaukrayinatag", "arbeitsgruppen", "instagramcomfashioncritic", "fatamorgana", "знаиua", "shellcompanies", "reuterscomизраильск", "uznayvseru", "hochuua", "naparisecom", "httpstcoucenttdjw", "httpworldofmartialartspro", "httpswwwgazetarupolitics", "facebookcomshurikdemchuk", "annnewsch", "httpwwwiarexruarticles", "ейфелемnppdcomua", "homosexuals", "muuttua", "httpsrueconomicsruregion", "источникhttpswwwobjectiv", "georgetown", "httpsxnsbbzcadxn", 
                     "httpsgenichanecomuamainnewsvschastlivcevoperekryvayutdorogunaplyazhdlyaavtomobilnogotransportahtml", "tvrusportfifaworldcup", "equals", "borgia", "newrucom", "bruselas", "httpscontwskonorsвсе", "evaluated", "httplvivcom", "twittercomfcshakhtar", "dsmueduua", "acompañar", "prus", "homoseksualnych", "secondincommand", "equator", "squashпорічк", "httpswwwmerriamwebstercomdictionarystadial", "radiotrekrvua", "bostoncom", "httpswwwglavcomua", "httpswwwfacebookcomdenislopatin", "construya", "guano", "httpwwwistpravdacomuaresearch", "httpstcoehfmeegm", "newsagent", "concisenewsglobal", "httpkobmediarup", "communion", "alexandernewskijkathedrale", "httpsyoutuberaycqrc", "quaid", "pictwittercomchdxihadld", "wwwkmruvrossiiistoriyarossiiskoiimperiipervayamirovayavoinaobektantirossiiskoil", "begrudge", "ramblerru", "httpstcodrtdlyhch", "aduanas", "qualitäten", "infomircomua", "milgovua", "httpstmehromadskeuaінстагр", "obstructing", "httpspdwcompwwa", "rgrureuters", "httpnewscomua", "abaliru", "солсбериheguardianден", "facebookcomрозгортан", "httpswwwukrinformrurubricculturevsemirnoenasledieuneskopopolnilosesetremaobektamihtml", "httpufbetnet", "httpwwwdsnsgovuauaendernapolitikahtml", "kontramarkaua", "forgetful", "httpssamaraetagicomrealty", "quartet", "httpdynamokievuablogandersonnamestolansini", "russophobie", "httprusrandru", "commits", "recompra", "wwwopennetru", "truckloads", "dozorkharkovua", "висловлюванняхfacenews", 
                     "httpkonanvestiblogspotco", "russkij", "corrupción", "httprusskievestirunovosti", "recomprar", "protectedhromadskeradioorg", "reevaluation", "guangdong", "newsrambler", "terrawomanua", "bankrupting", "continuarán", "rubricado", "httpscontwskonorsопределены", "bossmanquarshie", "httpsezosvitavsimorgua", "consensuado", "comentar", "wwwbbccom", "httpspeopleearthyaleedupaleoceneeocenethermalmaximum", "newsille", "httpswwwstoretheraptorscomraptorsdelonwrightjersey", "videohttpstcoaztagrctld", "healthinfoua", "gazetauaвстреч", "httpnaspravdiinfonovostihrambozhiykakvyglyadyatsamyekrasivyesoboryicerkvivmire", "httpsilavpravdebiz", "prosecutorgeneral", "quantico", "rumania", "cruising", "httpsquadrantorgauopinionqedgaysreallywantgaymarriage", "perusteli", "httpstcoktlkjcm", "gruppenzweiter", "httpstmepltrk", "httpsbonuseximbcom", "vestniksrru", "httpsdataoecdorgpensiongrosspensionreplacementrateshtm", "httpwwwprozaru", "forderungen", "httpsmotokvartalcomuazerkala", "ruso", "httpstcondhdisptpd", "trumpeted", "httpurainformcomrupoliticstrampplatitsotrudnikamizsobstvennogokarmana", "forgiveness", "httpsvkcomvideo", "httpdynamokievuablogkorolumerdazdravstvuetkorol", "locomotora", "альбомstylerrbcua", "rub", "oruzhieinfo", "quarterfinalists", "britischrussischen", "bruised", "pictwittercomdkoegtzws", "pictwittercomjicurvy", "postgraduate", "arvostelua", "httpscontwskonorsи", "наканунеfootballua", "httpsyoutube", "httpscensornetuan", 
                     "reporteruacom", "stejdobragmailcom", "realisierung", "orthodoxodua", "ruzici", "equation", "tcccomua", "drdaorgua", "trussell", "httpsdelouaecononomyandpoliticsinukrainekanadagotovitdljasshaposhlinynamlrd", "nhlcomkings", "aufruf", "crux", "dotcom", "reconstruct", "medcvgovua", "httpmamonttru", "httpscontwskonorsвидн", "egeeduru", "httpstcoesqrgji", "pictwittercomixpwdvwgk", "глобализацииhttprossiyaplyusinfooteresiksatanizmuuniatskiyurokdlконечн", "lnauinua", "comentado", "httpnewsbyeconomics", "adecuado", "boxingnewscomua", "comisso", "morgue", "wwwfbarchivevoynyikonfliktyxxvekatrivoynygeneralayudenicha", "httponlinelibrarywileycomdoijdpdf", "pruitt", "persuasions", "acompañamos", "corruptand", "infosamopomichua", "allyrussiaare", "mosruноволун", "newsyouучен", "worldcupblogru", "ámbitocom", "crimeauawordpresscom", "accomplices", "httpsgoodspblivejournalcomhtml", "forhttpstcoerqyoyzdb", "litcultru", "sicherungssysteme", "inspectorgeneral", "nfdpua", "northorg", "uefacom", "malariafreispruch", "adecuada", "чайcom", "krutost", "spirituality", "duam", "mallageofcompinfo", "gazetauaони", "wmgruppenauslosung", "videohttpsyoutubeafcmayahq", "rueda", "noruegos", "pictwittercomeeysyhvnx", "httpswwwfacebookcomsaakashvilimikheilposts", "completing", "httpscontwskonorsпоэз", "httpsstorinkamkievuaarticlephpid", "communicated", "httpskhmdepouaukr", "videohttpsyoutubekvbyiglg", "generalopzodessaua", "статьиhttpspublizistrublogs", 
                     "sorgt", "httpalexnewsrurossijskoe", "vestiukrcom", "compromete", "httpstcogjiixexqh", "httpstcornvlnls", "httpscontwskonorsс", "httpsbetainuanayaponiyunadvigaetsyatayfunprapirunvlastiprosyatlyudeyevakuirovatsyahtml", "httpstinyurlcomywg", "httpsyoutubenhoszhvoei", "pictwittercomftupekmm", "wwwtbucomua", "ramblerruчервипаразит", "newsobozorgчто", "httpslentarunews", "kyivtimecoua", "lowincome", "pictwittercomihjzxjeqif", "httpsyoutubehwxknpsge", "httpsgooglbjeby", "trumpputinpuppet", "basketcomua", "rukataan", "wwwperspektivyinfobookpervajamirovajavojnakluchistoriikhkhvekahtm", "wwwdosyecomua", "httpwwwvedasiteeditrupage", "shrugged", "destrucción", "ruotsalaista", "frustrado", "httpswwwinstagramcomgacmotor", "ruth", "httpspdwcompwlyu", "httpslifedeeperrupost", "infoindustriacomua", "ruspravdainfo", "shrug", "httpswwwesrlnoaagovgmdccggtrendsch", "httpstcombgkglzj", "topwarru", "molbukuaяк", "prorussia", "obsinua", "ausdrucke", "comparándola", "situados", "wwwsegodnyaua", "pictwittercommghplwvqg", "httpscontwskonorsзаметк", "httpsmasterpluscouagtenydlyastiralnyh", "httpcatholicnewsorguaodnostatevishlyubiufranciyidvarokipoto", "evacuate", "graduated", "hypeua", "devaluation", "serpregionru", "compraron", "школьниковhttpsgooglcibwwf", "znajuaнагадаєм", "engadgetcom", "httplingamanet", "pictwittercomsrfukxijr", "pictwittercomgkyoofi", "compares", "ruotsista", "punggyeru", "georgi", "korrumpierten", "russiaeventyandexru", 
                     "commands", "compost", "forgiven", "httpsgooglgwnohx", "leopolisjazzcomua", "тrueua", "competidores", "compostura", "viacom", "combats", "vseru", "voronzinua", "pictwittercomhvalg", "comprise", "tribunaua", "mailtosubjecthttpsaffpdwcomfpfbcqfmacadruemailsharingbodydadbddbdfdbddbdbddbddbdfdbedbfddbedbdbddbdbbdbdbdbdbadbbdeddbdbddbdbddadadddbedbdbbdbddbdbddbdfdbfdbedbdbdbdbdbdddbdbc", "yuliarussianfilmweekorg", "compostables", "httpmosvediruarticlehtml", "squarely", "zbruc", "httpsmukachevonet", "httpsnewsramblerruother", "httptvsumyuabezgotivkovyjrozrahunokukomunalnomutransportisumnezamanytplatnyhpasazhyriv", "zikuaотравлен", "httpscontwskonorsскорбь", "bankrupt", "httpehorussiacomnewnode", "httpnaspravdiinfonovostisamyegrandioznyestroitelnyeproektyvsovremennommire", "drury", "infrastructural", "thecitykievua", "dissuade", "quantified", "httptranskarpatianet", "discomfort", "newsmedia", "imghttpvoicesevasruhttpsppuserapicomcvdsyupxprqnljpgavaimgза", "änderung", "jamiroquai", "tvuaлетн", "pictwittercomppnxsjop", "rutte", "ruotsalaiset", "complejos", "tripadvisormfagovua", "kerouac", "httpsriaruworld", "playerunknowns", "abcnews", "fruta", "twittercomscuderiaferrari", "instagramcombogunok", "minregiongovua", "httpactualcommentru", "dakaitaowacomпереговор", "httpfbcomdwukrainian", "abbruch", "kuluttua", "httpstcoggpbsftykj", "perustelematta", "rubbed", "destabilisierungspolitik", "quartz", "фотоdnprcomua", "grund", 
                     "httpwwwyoutubecomwatchvpjbpgitbe", "vegecrimearu", "pictwittercombbhylaabci", "httpairportbyabouteapplicationsindividual", "apiprocoinbasecom", "commerces", "освітаua", "drugwar", "httpsrosmintrudrupensions", "graduation", "httpwwwcbrru", "palveltuani", "umolodakievua", "mydiscoveriesrupobyivalonamarianskoyvpadinyi", "skandalisierung", "httpsmmaprnewswirecommediacareerfairjpg", "httpstcoavvdnzilx", "httpsantikorcomuaarticlesgromkajaotstavkailidogovornjakisporoshenkovukrainskojpolitikezreetnovajaintriga", "ohuruogus", "selforganization", "kriminalukrainecomua", "apnewscom", "adecuadas", "httpstcojtgncczx", "httpsgooglctrmga", "combatir", "vgoruorg", "compraventa", "httpgooglrszb", "httpswwwukrinformrurubrictourismkakiekurortyvybirautukraincyetimletomhtml", "korruptionsniveau", "укропorg", "httpwwwusccborgmrcausesandcontextofsexualabuseofminorsby", "newsua", "squaring", "acompañados", "rubles", "threequarter", "aruna", "малюнкомtwittercomjimcarrey", "bitua", "mygiftua", "carlosperezumusiccom", "wwwukrinformua", "dozpcom", "instrucciones", "kartotekaru", "httpdocsgooglecomdocumen", "httpszemlyakinamerossiyacheybudetkrymnevazhnoeksdeputatverhovnoyradyzayavilchtosudbuukrainyreshatputinitramphtml", "contactkhgorua", "aufgerufen", "материаламhttpslentarunewsazovhttpslentaruarticlesukrflot", "cruze", "iansbengaluru", "forgoing", "spzhnews", "рбкhttps", "flickrcom", "timeuainfo", "gorgeous", "uaсум", "twittercomwoundfreeze", "duarte", 
                     "alsorussias", "matthewginfiniteglobalcom", "molbukuaвін", "httpnaspravdiinfonovostipadeniebitcoinostanovitnelzya", "httpstcokscnqrhr", "pizzatravelcomua", "httpscontwsjrstihiolge", "vokrugу", "rutschte", "friendmfagovua", "newsoneв", "httpwwwcolumbiaedujehmailingsrockdustinfarmingreduxpdf", "emracom", "pictwittercomnmarzpmbo", "prportalcomua", "disrupted", "httpsyoutubehonqxqpgo", "comprometió", "prut", "beeindruckte", "pictwittercomdantmhmnhq", "матчаsportua", "httpurainformcomrusocietyrfikitajprovodjatsverkhsekretnyerazrabotkinovogovidakosmicheskogo", "pictwittercomffrpamqik", "httpswwwvestirudochtmlid", "wwwdjournalcomua", "quakes", "vanuatus", "vitiligofriendsorg", "httpsyoutubeshmtpzd", "pictwittercomlrldshj", "outofcompetition", "vndsnsgovua", "памятиageofcompinfo", "httpstcorcelurss", "ruidosa", "irrupción", "beautyua", "httpanonszakcomua", "sicherheitsorganisation", "manutdcom", "httpswwwstoretheraptorscomraptorsalfonzomckinniejersey", "situated", "comforting", "trunk", "inhttpstcoizokduqe", "opticluborg", "drugged", "wwwpravoslaviehtml", "httpasninuauanewsnewsproduktyvkrymuvsetipokazalizhutkiefotohtml", "tengrinewskz", "httpwwwyaplakalcomforum", "overclockersua", "bytribunacom", "httpspdfssemanticscholarorgadcccadfaaddbpdf", "riaru", "maildosyecomua", "httpsvkontakterusharephpurlhttpsaffpdwcomfpfbnzfmacadruvkontaktesharingtitledddbfdbdbdddbadbdfdddfdeddbfdbddbbdbdbdbdbdbdbdddbdbdbdaddbdbdbdbdbdbcdbddbedbcdbcdbeddb", 
                     "httpotgcnua", "httpurainformcomrupoliticsmeksikaikanadadogovorilisokruzhitsshaekonomicheskineobosnovannymi", "httpssoundmaguacatalogamplifter", "моршинприкордонникhttpforpostlvivuanovynynalvivshchynizaiavy", "beirut", "httpswwwfacebookcomgacmotor", "httpdocmerudocan", "партияновоготипаhttpsnarzurrukhitryjjpla", "newslandcom", "izbrannoecom", "httpsdocsgooglecomformsduwymhhfjctxpedondkaforkdujmoaansrtzbrsediteditrequestedtrueдовідководмитр", "nowthisnews", "russlandbild", "depouaміжнародн", "аgroportalua", "councilgovru", "perui", "httpurainformcomrusocietyukraintsamsovetujuttschatelnejotnositsjakprotsessuvyboryturoperatorov", "pictwittercombcmgomkdcy", "httpswwwereadingmobibookphpbook", "sdcreateelementscriptssrcembedflowplayerorgembedminjsdbodyappendchildseslicecalldgetelementsbytagnamescriptparentnodewfpespusheelcratiortmplivefalseoriginhttpsuaatobogivoynyvshtabeoospokazalikaktreniruyutsyaukrainskieartilleristyhtmlanalyticsuakeyswfreleasesflowplayerorgcommercialflowplayerswfswfhlsreleasesflowplayerorgcommercialflowplayerhlsswfadaptiveratiofalseclipsubtitlessourcessrchttpsviduafileshrmpsuffixmptypevideomp", "destruir", "httpsyoutubeshpegexw", "turunen", "companylabour", "httpscontwsjrjuzhnorusskijкто", "competitividad", "commercialised", "мессіsportexpressru", "openstreetmaporg", "situational", "pictwittercomxpfutfvjtu", "httpsgooglvtinсайт", "wilsonsunginfortrendcom", "httpукропorgпр", "instagramcomkourtneykardash", "arun", 
                     "brunnstrom", "httpsmasterpluscouagstyokladverkidlya", "regierungsvertreter", "pictwittercomekhisd", "вetainuaфанат", "eighttimes", "wwwterrawomanua", "httpdetectormediarinokarticleuparlamentizareestrovanoproektprozminidozakonuproderzhavniikomunalnizmi", "trumpies", "cuantía", "minenergogovru", "onlineuaпрезидент", "pictwittercomhscxcol", "inspiredcomua", "comprometida", "httpcominkmugovuacontrolukpublisharticleartidcatid", "comercializadora", "mediahttpsvideotwimgcomexttwvideopuvidxxtzaykbobxrwrmmp", "vogueru", "pictwittercompmjvyqzh", "wwwstoletieru", "wellorganised", "тснuaго", "httpstcocxvlcwhjls", "xhnews", "vnnpugovua", "viruses", "$documentreadyfunctionboxznuacommentsinitcatche", "twittercomlstotch", "druglaw", "organisierte", "complicate", "míru", "капецьhttpstcopiwvxxddbx", "propermru", "висловлюванняхfacenewsнажм", "httpswwwnceinoaagovsitesdefaultfilessitesdefaultfilesdecemberglobalsignificanteventsmappng", "donnabaeduua", "httpsyoutubezoabmeooq", "webapexcomuaecommerce", "tua", "httpsderzhavasvetawebnoderunewsanomaliivprirodeipogodetornado", "insorg", "facebookcombrigade", "mosru", "httphandcashio", "pictwittercomzdnhqhl", "ruska", "httpsapostropheuaarticle", "wwwlvivhiphopallstarcom", "faktyua", "showdreamorg", "ilikenewscomua", "httpnaspravdiinfomirvelichayshieaferyvistorii", "rupaulsdragrace", "auffahrunfall", "httpurainformcomrueconomicsstaliizvestnyoblastisnaibolshimdolgovymbremenempozarabotnojplate", "sportboxru", 
                     "знаютhttpstwittercomcrimeauastatus", "kinokingdomcom", "httpsmoikrugrushareurlhttpsaffpdwcomfpfbcqfmacadrudcdbedbbdbadddbsharingtxjhemuvomoikrugtitledadbddbdfdbddbdbddbddbdfdbedbfddbedbdbddbdbbdbdbdbdbadbbdeddbdbddbdbddadadddbedbdbbdbddbdbddbdfdbfdbedbdbdbdbdbdddbdbc", "russlandkennerin", "militaryrussiaru", "ruf", "httpstwittercomintenttweetsourcewebclienttexthttpsaffpdwcomfpfbcqfmacadrutwittersharingdadbddbdfdbddbdbddbddbdfdbedbfddbedbdbddbdbbdbdbdbdbadbbdeddbdbddbdbddadadddbedbdbbdbddbdbddbdfdbfdbedbdbdbdbdbdddbdbc", "kurumi", "noncombustible", "instagramcomzelenskiyofficial", "ruпропаганд", "agronewsua", "instagramcompeskovakaterina", "nearlycompleted", "belarusian", "guardar", "krimrussischen", "equalised", "httpscensornetuaпереглядів", "afpcom", "comprobar", "composting", "wwwxxlkadetiruskorpushtmhram", "tofightru", "eastdaycom", "httpwwwmkrusocial", "complicados", "apostropheuaфутболист", "cndsnsgovru", "httpwwwgolosnocomua", "httpswwwrferlorgatrumpdoesntr", "httpdynamokievuanewsraspisaniematchejiteletranslyatsijchmnaiyunyapervyiematchifinala", "sumual", "bruyne", "httpsgooglnvhqk", "httpswwwccncombitcoinandether", "httpsmasteroklivejournalc", "steuererleichterungen", "httpasninuauanewsnewsvsetipokazaliunichtozhennujunadonbassetekhnihtml", "httpswwwinstagramcompbkdbzuawmhhlentakenbykasperschmeichel", "elfimovamarusya", "focusua", "zentrums", "cometer", "farruggio", "kurkulcom", "commando", "ruckus", 
                     "httpwwwfacebookcomdialogsendappidredirecturihttpsaffpdwcomfpfbnzfmacadrufacebookbmessengerbwebsharinglinkhttpsaffpdwcomfpfbnzfmacadrufacebookbmessengerbwebsharingdisplaypopup", "shrunk", "weißrussland", "httpsyoutubewnwypif", "rekrutierungspersonal", "governmentrun", "complemented", "accommodate", "squabbling", "onodua", "httpsruwikipediaorgwiki", "nimruz", "compatriot", "accompany", "advertmirtesenru", "hintavertailua", "httpswwwdailykoscomstoriestheantarctichalfoftheglobalthermohalinecirculationiscollapsing", "storinkacomuaна", "competencias", "trukhaniv", "infrastrukturminister", "vkcomstrelkovinfo", "lewadazentrums", "forthcoming", "pfcstalcom", "httpswwwsegodnyauaimgarticlemainjpg", "fwdailycom", "instagramcomsunsmaker", "mediumhttpsreplyuanetuploadspostscadfbaecbdрф", "reconstruir", "cruce", "crimerussiacom", "restplacecomua", "httptsnuavideovideonovini", "antikorcomua", "httpswebcachegoogleusercontentcomsearchqcachexiahzzxcjhttps", "httpszenyandexrumediaelmuridtrampikrymbfdfeaadf", "guadalajara", "dualrotor", "httpsdropmefilescomvolfs", "roiru", "comparatively", "wwweconomistcom", "wwwyoutubecomwatchvzifndftipq", "emigradosru", "countrylivingcom", "mainostettua", "httpslentarunewmmediumsocial", "interrupt", "ruv", "httpsriafanruvyrazhaiteprotestsobiraitetolpusshastoyatnaporogenovoigrazhdanskoivoiny", "georgiy", "actualnewsorg", "cruised", "httpsmmaprnewswirecommedianchainlogojpg", "communiqu", "acom", 
                     "sanctuary", "comparative", "charukesi", "httpregulationgovruproje", "месяцаageofcompinfo", "urainformcom", "ubruaоднак", "muammar", "тodaycom", "expressbuskievua", "twittercomfssrbije", "rtcom", "mailtosubjecthttpsaffpdwcomfpfbnzfmacadruemailsharingbodydddbfdbdbdddbadbdfdddfdeddbfdbddbbdbdbdbdbdbdbdddbdbdbdaddbdbdbdbdbdbcdbddbedbcdbcdbeddb", "httpsyoutubelrbdorxjqyt", "acomodó", "quasireligious", "interactuar", "cruzándose", "httpsuspehrussialivejourna", "httpsmoikrugrushareurlhttpsaffpdwcomfpfbnzfmacadrudcdbedbbdbadddbsharingtxjhemuvomoikrugtitledddbfdbdbdddbadbdfdddfdeddbfdbddbbdbdbdbdbdbdbdddbdbdbdaddbdbdbdbdbdbcdbddbedbcdbcdbeddb", "reutersdpabrusselsberlin", "instrumentos", "httpseconomicsunianua", "fcmetalistcom", "rundfunkbeitrag", "httpscontwskonorsпод", "zdravoecom", "плоua", "sobturcom", "pivdenukrainecomua", "httpsenwikipediaorgwikiwhitehousepresscorps", "httpviknastbua", "saguaro", "ruanda", "marinadmitruk", "selfrule", "httpskulturologiarublogs", "муфлониnppdcomua", "varustettu", "comida", "httpswwwstoretheraptorscomraptorsmalachirichardsonjersey", "httpsyoutubeewrjzortuy", "fakenews", "httpwwwliruinterfacepdajidpidredirectedpagebackurlusersbabetalizapost", "shigeru", "httppravosudijanetarticleprezidentiranavhodevolevoyborbypostavimsshanakoleni", "pictwittercomaosawhkd", "instagramcomspltfc", "trucker", "wwwtezanrurushtm", "ernährung", "httpnaspravdiinfonovostisamyebogatyesemimira", 
                     "httpscontwskonorsждёмс", "coma", "combustibility", "pictwittercomjzhjswmv", "kolesaru", "puntualizó", "complicado", "newspeak", "прохожимmediahttpswwwyoutubecomwatchvurjkqvsec", "httpsfbcomhromadskeuaтвіттер", "balaboikoromagmailcom", "habitual", "complication", "httpssfckcomua", "olorunnipa", "brunt", "httpselikyinuaкрім", "restructured", "httpsglavcomua", "httpsmasterpluscouagsmazkidlyastiralnyh", "comercialización", "httpsyoutubeccmuhpqsu", "scrutinized", "stutteringjohnpodcastlibsyncom", "druk", "httponlinelibrarywileycomdoiglabstract", "pinterestcom", "grumman", "truthfully", "dramacomedy", "wwwbelrussiapageidhtml", "varustettujen", "httpstwittercomcrimeauastatusфот", "httpwwwgovbccagovcontenttaxesincometaxespersonaltaxrates", "acompañó", "wwwknliferu", "compartir", "httpstcojzioskeh", "httpstwittercomhromadskeuaгугл", "homoseksualistów", "combustibles", "disuasorio", "httpdozorkharkovuahtml", "wwwfacebookcomvoinamato", "httpwwwpsychologiaeduplczytelnianiebieskaliniaprzemocwzwiazkachhomoseksualnychhtml", "situadas", "httpsukrainarunews", "rumored", "httpstcoyxpbjmjme", "httpszakarpattyanetua", "bruto", "vestiruелисе", "newsbiz", "wwwjbalvincom", "pictwittercomnvlgyqvw", "httpstcoqzththlva", "wwwmagazindomovru", "httpsjoinfoua", "issuance", "httppatriotyorguaimagesaklargejpg", "pictwittercommlfrnzivd", "хочуua", "pictwittercompolekbpw", "httpswwwrbcrurbcfreenewsbbaded", "expresuanewsposolsshaestoniyipodavvidstavkuzayavytrampa", "gismeteoua", 
                     "pictwittercomxmvtuocfq", "исследованияhttpantifashistcomitemos", "kingsofaircom", "dmytruk", "volyncomua", "accomplish", "httpsgooglznbv", "acemodelcomua", "httpsofdru", "coorganized", "httpsyadiskdfxxkidcxolum", "annanews", "nhsfightbackorg", "httpsvzrunewshtml", "compellent", "januarymay", "uaa", "comandaba", "симферополемhttpsrukrymrcomanewshtml", "httpgupkrymenergocrimearuconsumerscservoffices", "disrupting", "gruyter", "httpswwwfacebookcomlvivhiphopallstarpage", "masslivecom", "svobodaorg", "beeindruckend", "widerrufen", "moorgate", "bladenewsжурналіст", "olympicua", "individualizada", "httpstcoqnghnjopn", "rubric", "httpsvkcomglobalpolitik", "aspicomua", "httpstcoeahdvby", "httpswwwukrinformrurubricsocietymidposovetovalukrainskomvnimatelnovybiratturoperatorahtml", "alaniatvru", "portuarias", "pictwittercomgmcizoywfh", "httpdynamokievuablogurugvajportugaliya", "seksuaali", "vokrug", "httpswwwpiotrskargaplzwiazkihomoseksualneihomoseksualizmraportikomentarzmedycznyihtml", "httpswwwncdcnoaagovsotcglobalsnow", "conceptual", "tophitruв", "httpsantikorcomuaarticlesavtograhdankasushchestvennopodorohaet", "findfaceru", "uruguayans", "organizadores", "rfsru", "hydrodredgercom", "opennetru", "httpsgooglcpwx", "jaettua", "tvigleru", "henkilöperusteisia", "httpsfritzmorgenlivejournalcomhtml", "playmrtcommk", "organisationen", "beeindrucken", "kavkazcentercom", 
                     "httpsmydiscoveriesruuchen", "httpasninuauanewsnewsberemrpgipoukrainculetnijjmalchikizdnrrhtml", "vservua", "httpdynamokievuablogktoskazhetchtorezultatnespravedlivyij", "odtpomrodessaua", "footboomcom", "comprehensively", "ruleeasing", "virulent", "wwwzhenskoeschastiecom", "commenced", "actualización", "northcom", "guardianвідповід", "кrutost", "httpwwwpravdacomuarssviewmainnews", "rtrussian", "httpswwwkommersantrudoc", "pixabaycomfreephotos", "somnuak", "httpsgoogldtuja", "drum", "словахhttppolitikusru", "trikratyblogspotcom", "dneprcomua", "mskmyargmailcom", "holaollycom", "youtuberuslanatube", "euassembled", "nchaincom", "comics", "zaryaluganskcom", "httpkmnetshops", "outcomes", "beanspruchen", "pascual", "heterosexual", "homoseksualizmu", "ruai", "httpswwwvestirudochtml", "cruelly", "httpnewssevascomregioncrimeaincidentgradvdzhankoefotoiyun", "qualification", "httpswwwvestirufifaworldcupgames", "rudkovskayaofficial", "romualdez", "httpsprojektesueddeutsche", "naukavestiru", "comprising", "tvru", "actuado", "houzzru", "frustrations", "googlecom", "commemorate", "ruthlessly", "pictwittercomxhojnehoc", "dpinformatorua", "guarantees", "httpswwwyoutubecomchanne", "guardiola", "deutschrussischen", "ukrkinocomua", "heterosexuality", "fttccomua", "brunches", "suara", "homoseksualizm", "infraestructuras", "jurisprudence", "comparable", "сегодняua", "tregua", "iuatv", "dniru", "httpswwwyoutubecomchannelucvf", "badcomedian", "russischsprachigen", 
                     "peruspalveluministeri", "fruitful", "entrusted", "annäherung", "ruins", "hervorgegangen", "soundcloudcomboovyeah", "районinua", "reconstruction", "compañera", "facebookcomwwwvdvmilgovua", "httpscontwskonorsсегодн", "comisionado", "compounded", "pptonlineorg", "httpshottoursinuahottours", "httpsikstvru", "ruslovoidiloua", "$ageofcompinfo", "vkcomzahidnatochka", "scplnpugovua", "rumberos", "beeindruckt", "ipressua", "facebookcomaleksejgolobuckij", "yahuixinhua", "euronews", "comey", "sorgen", "disruptive", "vkcomroscosmos", "tuinukuafe", "nahnewsorg", "secondquarter", "wwwfivborg", "httpscontwskonorsза", "oua", "continual", "zerstörung", "bodyguard", "grundgesetz", "composer", "pictwittercomaewikfo", "comprehend", "russianled", "comedies", "starylevcomua", "georgischen", "httpstsargradtvarticlesg", "commissioners", "informzpua", "mirvokrugblog", "newssportboxru", "comedians", "narodnapravdaua", "suarezs", "continuar", "cuarta", "monstruo", "httpsbitlykctbff", "kpru", "putinru", "commemorating", "httpsinosmirupolitic", "httpscontwskuropyatnikoff", "welcoming", "httpswwwtechnoparkruholodilnikifiltpriceto", "голосuaсообщ", "facebookcomboovyeah", "sudua", "podrobnostiua", "organ", "minfincomua", "informatornews", "sportifua", "russiangerman", "actuales", "presszhblogspotcom", "lithuanian", "httpscontwsстран", "годуrussianrtcomмнен", "cftsorgua", "instructive", "wwwunianinfo", "milru", "loveopiumru", "rueters", "pictwittercomqczgshtmhq", "gheorghe", 
                     "zusammenbruch", "russо", "youtubecomxl", "molbukuaзазначаєт", "individually", "quicomoit", "structurally", "antigua", "бортникrussianrtcomмнен", "httpfinfrontru", "ukrsegodnyaua", "guangzhou", "compromise", "ovariorum", "httpswwwfacebookcomjulialacrima", "commissos", "тесленкоalternatioorgмнен", "restructure", "incoming", "facebookcompressjfonews", "runway", "promancomua", "competitively", "httpsmastervisitrusemeynayafotosessiya", "moscowpostcom", "ukrainaru", "httpsvirtusua", "httpistmatinfofilesuploa", "commends", "sicherheitsorgane", "коммерсантru", "bkewbreitbartcom", "ctrcenterorg", "httpsmastervisitrudetskayafotosessiya", "httpstcosngvqe", "facebookcomtamaramaiochi", "noncombatants", "organophosphates", "ivasinews", "prosoccerusacom", "regionewssumyua", "competitor", "pictwittercomydyayy", "smartclevercomua", "orbitadnua", "gurung", "competición", "vidrorbcua", "httpstsnua", "organizaciones", "cuadro", "cometido", "vorgehen", "organiser", "composition", "druck", "newshour", "obstruct", "superagronomcom", "httpscontwskonorsпроверк", "світua", "salesruinfortrendcom", "httppatriotyorguaimagesakjpg", "httpsnewsfrontinfo", "vokrugsvetaua", "trumpilta", "httpwwwodigitriaby", "higuaín", "httpchelinecomua", "vicom", "squash", "guru", "pictwittercomquvbuoh", "castrum", "textualist", "georgias", "competitiva", "antitrust", "khvgorodeua", "httplodagovua", "rvnewsrvua", "graduate", "antitrump", "cirrus", "fightnewsinfo", "mundodlavozcomar", "conservativecom", 
                     "trumpeter", "organisational", "berufung", "pictwittercomhbqdmkgdi", "httpscontwskonorsвсё", "equated", "gxnetua", "kulkua", "completo", "prorussian", "ahuacatl", "recruit", "georg", "militaryrun", "вінfacenewsнажм", "rubble", "qualifications", "vestiru", "constructing", "quarles", "cityadmlvivua", "kpua", "httpwwwsvobodaorgahtml", "httpscontwskonorsэмоц", "nbcnewscom", "marruecos", "rußpartikeln", "overrun", "situaciones", "drugmaker", "httpscontwskonorsзашёл", "httpscontwskonorsреш", "evacuated", "httpscontwskonorsзавтра", "eucom", "commanderinchief", "httpswwwgosrfru", "continuación", "intellectualism", "pictwittercomrrzcjchag", "wwwukndcomua", "sallittua", "devaluación", "marenostrum", "compute", "agronews", "anews", "competitions", "quarterback", "httpsradiomayakru", "comienzan", "newscomua", "огоua", "acccvua", "patriotyorg", "profidomcomua", "ipnewsinua", "stockinfocusru", "georgian", "guarded", "arabiclanguage", "rudovanata", "twittercomhromadskeua", "comunidades", "pictwittercombbkenlkog", "medhealru", "тижденьua", "racursua", "actuality", "compromatws", "disfrutar", "forged", "facebookcomshirlpotter", "httpdpoblastonline", "ldufkeduua", "еru", "weltgesundheitsorganisation", "cruzar", "httpswwwfacebookcomevents", "facebookcomgroupszahidnatochka", "bagnetorg", "httpcndsnsgovua", "vereinbarungen", "pictwittercomcsktdaayw", "giorgio", "higuain", "rumailah", "evaluation", "physorg", "twittercomfifaworldcupru", "httpsdpinformatorua", "womanru", 
                     "pictwittercomecmdnj", "pictwittercomoyndigub", "sexually", "tjournalru", "gianlucadimarziocom", "kinoteatrru", "wwwstarsliferu", "noruego", "onequarter", "rudkovskaya", "dpsugovua", "httpscontwskonorsдве", "vestuario", "вінfacenews", "sru", "commonly", "pxherecom", "interruption", "rust", "commissioned", "welcomes", "kkwbeautycom", "busforua", "newswire", "longrun", "competed", "pictwittercomaxntycrozw", "facenewsу", "httpgordonuacomnewsworldnewsglavarazvedkipentagonaurossiiikitayavblizhaysheevremyapoyavitsyakosmicheskoeoruzhiehtml", "ormfagovua", "klitschkobrotherscom", "uruguaya", "httpsinosmirupolitichtml", "pictwittercomcggzghfse", "compagni", "pictwittercomgpsukujao", "leiua", "ecuadorian", "httpscontwskonorsв", "situar", "patrullera", "guardion", "trudeaus", "facenewsв", "commandments", "httpscontwskonorsмои", "crumbling", "vorgängerorganisation", "agropolitcom", "aquatic", "quantum", "cihuatlan", "dicomo", "httpscontwskonorsне", "recomendado", "opogodeua", "domikua", "evaluar", "shortcomings", "cuarto", "httpstconssmpqyfhm", "rumanía", "ruskava", "ruft", "httpldufkeduua", "syncrude", "combative", "noncompliance", "instagramcomrealdonaldtrump", "iskrakungurru", "nikopolnewsnet", "instructed", "communists", "begdpua", "helirussia", "fcbukovynacom", "httpsinterfaxcomuanewsgeneralhtml", "recommends", "httpscontwskonorsпесн", "httpsgooglveljta", "pictwittercomnckzxzs", "carru", "lamduan", "intruder", "newsразведслужб", "aufgrund", "swnscom", "pravmirru", 
                     "mindua", "httpwwwbistroenglishcom", "httpswwwpolitnavigatornet", "lengua", "horrorzoneru", "trumpedup", "pictwittercomgfeaucebhc", "sprung", "homecoming", "httpsgoodspblivejournalco", "drummer", "httpsavtonovostidnyaruavt", "httpsdocsgooglecomformsdefaipqlsecyuzinhzmkyaffucmygucjzkshkjxmtciwviewform", "pictwittercomhdeetmnli", "crushed", "firstquarter", "вестиua", "officeruspiperu", "comparing", "глянецcom", "newsrooms", "compensar", "casual", "recruits", "httpscontwskonorsмчит", "pictwittercomdjccqrg", "kievvlastcomua", "оpogodeua", "httpswwwukrinformrurubricsocietyiunanarodnyjkalendariastrovestnikhtml", "druids", "httpdynamokievuablogotkudanogirastut", "артищенкоversiaruмнен", "httpwwwbistroenglishcomrazgovornyjanglijskijdlyanachinayushhihsnulyakakuchit", "httpswwwcomuaarticlesravneniematerialovnovostroek", "lauantaita", "ladyhealthcomua", "бабицкийliferuмнен", "guadalupe", "рисункомtwittercomjimcarrey", "httpstcosrywrcrd", "dualrail", "borussia", "httpkmnetalladsadsinstruction", "showrunner", "bundesregierung", "thrust", "httpswwwznakcom", "rubrum", "ruetz", "httpsgooglcbxg", "supremeru", "omrgovua", "школярівhttpsgooglcibwwf", "russischer", "ruserree", "kprfru", "recommend", "httpstwittercomiamfrimpon", "instagramcomzahidnatochka", "horgan", "httpwwwsciteclibraryruruscatalogpageshtml", "bruno", "uav", "httpstcouhltqteg", "httpsportanalyticcom", "ruined", "coastguards", "dynamokievua", "httpswwweximbcomukraboutpressn", "communicating", "homosexuality", 
                     "guan", "instructor", "autonewsua", "tenews", "twittercomwbsuperseries", "daykyivua", "elcomartua", "compromatgroup", "incongruous", "stadtregierung", "uagoloscom", "httpsfasorgsgpcrsnatsecifpdf", "russiansourced", "rusjev", "gvodafoneua", "twittercomvasylkyrylych", "rupture", "verursachen", "admagazineru", "obstruction", "ntktvua", "inopressaru", "httpurainformcomrusocietyshvetsijaotkazalasbojkotirovatchempionatmira", "cuales", "compañeros", "commentator", "праваhttpdannewsinfo", "pictwittercomewqehtcp", "kriworutschko", "äußerungen", "combinada", "httpswwwfacebookcom", "staterun", "compromises", "inadequately", "comprises", "информua", "communitysupported", "commenting", "httpstcoudsasem", "aprueba", "gazetalvivua", "httpsgooglvtin", "compra", "puhua", "rubin", "ehorussiacom", "disruption", "yоutubecomwatchvuywicwitw", "zaokruglennya", "facebookcomvasilenkodarya", "httpsplusgooglecomhromadsketvu", "boxingscenecom", "facebookcomeffatoothbrush", "pictwittercomupmwccq", "russianfriendly", "instagramcomelizabethstewart", "httpwwwvarashinfo", "actuaciones", "comunidad", "pictwittercomlsfiykhakk", "rumasa", "commit", "nashreportercom", "httpszagonkaruserialy", "trusted", "httpstcohavyiaqrm", "newsmarist", "orgullo", "compare", "construido", "usuario", "riafanru", "eventual", "stardateorg", "cuadrados", "rbcua", "fullpictureru", "sportarenacom", "construcción", "httpwwwpnasorgcontent", "httpswwwfacebookcomgroupshelpfarmugastanislav", 
                     "facebookcomportnovandreyukraine", "gruppe", "februar", "httpsrukrymrcomanewshtml", "glavnoeua", "incomplete", "wikipediaorg", "forgotten", "commentators", "gottstatcom", "газетаzpua", "antirussischen", "durdominua", "deloua", "crush", "pravdacomua", "compensate", "httpstutby", "construir", "pictwittercomawqbldxgxi", "vimpelcom", "común", "httpsfbcomhromadskeua", "campeonesua", "trustworthy", "distrust", "organize", "pictwittercomkdysonac", "decadeshttpstcofomgqzyow", "estructura", "compiled", "tijuana", "trumpputin", "organizational", "ruiz", "pictwittercommbgbcgwhc", "instagramcomerikaherceg", "wwwairbnbru", "mknpugovua", "coruña", "httpnaspravdiinfonovosti", "znakcom", "httpswwwcouchsurfingcom", "httpstwittercomhromadskeua", "alsorussia", "pravdatutua", "instagramcomsambirspilnotatvogomista", "centerconceptual", "httpscontwskonorsпро", "ruido", "kasparovru", "crucially", "medikforum", "rosprescom", "rumours", "brundtland", "pictwittercomcojqxfrbiv", "esnews", "dutchtt", "facebookcomgroupsтипов", "crunch", "tacoma", "equally", "httpswwwfacebookcomterrikon", "pictwittercomahfvupieg", "miningforgood", "persuaders", "haluaa", "organising", "httpscontwskonorsя", "adequate", "pictwittercomxhfmklsjn", "rußpartikel", "rufián", "internetua", "wuzzupru", "committees", "brutally", "morgana", "durchführung", "httpshromadskeua", "mediumcom", "patriotyorgua", "dpainternationalcom", "composure", "runnerup", "structuring", "httpstcombfbiueemq", 
                     "matchdayua", "olegasvideocomua", "valuable", "ruina", "taruta", "newsfinanceua", "httpscontwsvladal", "pictwittercomzxxhzxlf", "httpstmehromadskeua", "russisch", "facebookcomмакар", "httpstmeif", "newsru", "censornetua", "russischorthodoxen", "safeguard", "yuliyapavlovagmailcom", "novateru", "httpsgooglevzwmg", "russlandexperte", "bbccom", "httpchodtrkcomua", "rubber", "nothingtrump", "unsplashcom", "neocommonwealth", "gettyimagescom", "qualifier", "fckarpatycom", "gradually", "trinixyru", "quashed", "httpscontwsashacontws", "pictwittercomjbftdgmka", "googlecomua", "pictwittercomcuxlaoqg", "constructed", "gogetnews", "eruption", "sunpugovua", "gazetaru", "compromiso", "вступосвітаua", "facebookcomnationalbankofukraine", "httpsgooglsnvjv", "comfortably", "actualmente", "dual", "dnews", "облакоmailru", "threerun", "fuat", "httpscyberberkutorg", "abruptly", "rubbish", "httpstmekorrespondentnetджерелоkorrespondentnet", "forgot", "autoriacom", "icomos", "wwwemazecom", "organizar", "httpscontwskonorsразговор", "httpamarketsorggukxg", "scrum", "httpschervoneclivejour", "httpstmevmestezp", "commonswikimediaorg", "pictwittercombfodcljky", "ilentacom", "ruotsi", "medicua", "stuart", "zikua", "trusts", "pixabaycomumihir", "thebroccolitrickcom", "ustruppen", "destructive", "eduardo", "squawka", "antikorcom", "rusjevnet", "bankruptcy", "runoff", "rukrymrcom", "besorgt", "pictwittercomtlobbdb", "pictwittercomhbczxcgdl", "euaci", "zidnua", 
                     "httpscolonelcassadlivejournalcomhtml", "runners", "comprised", "radiosvobodaorg", "tehnotcom", "erupted", "gradual", "rushed", "completion", "mycitymkua", "abrupt", "boscombe", "dnewsdnua", "newsinfo", "compañías", "httpperevodikaruarticleshtml", "renaissanceconstruction", "organisers", "organisiert", "runewsmedia", "commodities", "tvkrua", "comfort", "mutually", "instagramcom", "aguas", "managua", "gzetazpua", "belarus", "interfaxcomua", "facebookcomtaladidenko", "httpswwwyoutubecomwatch", "newsoneua", "httpwwwyoutubecomchannelucaj", "httpvkcomictvua", "computers", "comunicado", "aqua", "prnewswire", "russlandreise", "kafanewscom", "newsfront", "languages", "brutality", "uatv", "compassion", "newsyouinfo", "krua", "filmfreewaycom", "instagramcomkatyperry", "trucking", "longrunning", "uareporter", "pictwittercommfyqoqnig", "georges", "compartmentation", "erveuagmailcom", "korruption", "facebookcomborisovcharov", "topnews", "cuadrado", "truppen", "arguably", "rulesbased", "noruega", "wiederum", "ruta", "newsom", "uazmi", "httpsssl", "rulings", "footballukrainecom", "clutchua", "pictwittercomdsjjlov", "tworun", "glavcomua", "teamrussia", "ruptly", "disruptions", "cruises", "usuarios", "instagramcomvkozlovskiy", "sinoptikua", "migcomua", "sportunianua", "khersondailycom", "commissions", "organizer", "dimariapictwittercomwdrvfjouie", "ritual", "mcquaid", "compound", "nahuatzen", "recommended", "facebookcommozukr", 
                     "$datepickersetdefaults$datepickerregionalru", "gorodcnua", "espncom", "touareg", "vereinbarung", "continually", "quantitative", "trumpin", "malininformcom", "combines", "mutual", "autonews", "foxnewscom", "evaluate", "httpsinstagramcomhromadskeua", "facebookcomtetianamontian", "xsportua", "commented", "aquanaut", "instagramcomronaldo", "georgien", "zagorodnacom", "googleanalyticscomgajs", "facebookcompeopleвячеславпечененк", "evacuation", "httpdumskayanetnewsnaodesskomplyazhepoyavilsyaogromnyymuralv", "recommendation", "crudo", "igualmente", "httpsdocsgooglecomformsdefaipqlsfefxkjdvlyigkjsuksdaguvvbrqienwwflwkiuorqviewform", "filmua", "russell", "gruender", "cruise", "nppdcomua", "newssvobodafm", "ftqconstruction", "futuristru", "httpwww", "httpwwwxxcenturecomuaa", "compliant", "putintrump", "comeback", "rsportru", "frontrunner", "farrugia", "fromuacom", "virunga", "dwcom", "pictwittercomhhbgdqjq", "comcast", "rusa", "korruptionsbekämpfung", "httporduacom", "comosa", "mlbcom", "ruban", "fbuua", "composite", "comercial", "blackseanews", "facebookcomvlv", "jpmorgan", "combinado", "comenzó", "facenewsua", "ukrinformua", "pictwittercomyytgnebvi", "ohuruogu", "httpsvkcomwall", "kuala", "competence", "förderung", "lazurnoecom", "спортua", "runner", 
                     "httpstcoaljjocrx", "organizing", "finanzru", "russianamerican", "guaranteeing", "instructions", "westnews", "ainua", "facebookcommnsifr", "competitors", "orduainfo", "frustrated", "httpfaktyictvua", "instagramcomrealpotap", "btuorgua", "comparison", "vkcomgeopoliticsrussia", "comisión", "russo", "wwwfainaideacom", 
                     "khersonnetua", "frustration", "twittercom", "sexuality", "guaranteed", "nostrum", "instagramcomemrata", "keetharuth", "commonwealth", "icom", "cruelty", "rupert", "comic", "pictwittercomjucwonmvq", "crimeaua", "ukrnewsinfo", "complying", "pogliadua", "russen", "uraru", "compulsory", "fifaworldcupru", "graduating", 
                     "commanding", "internetuacom", "orduabiz", "commerzbank", "gofundmecomtogetherwithstanislavfarmuga", "rugby", "dailytechinfoorg", "странаua", "httpglavredinfo", "actualidad", "component", "httpstwittercomictvfakty", "erveua", "httpscontwskonorsо", "xinhua", "actuación", "incomes", "httpbitlyfaktyictvchannel", "frustración", "sqcomua", "commentary", "spectrum", "rabotaua", "command", "httptksua", "dynamomaniacom", "factually", "facebookcomdtpkievua", "nicaragua", "httpstwittercomkrimrtstatus", "goroddpua", "instrument", "pictwittercomicvreqfvh", "valuation", "httpswwwfacebookcompermalinkphpstoryfbidid", "avtodreamorg", "agua", "kuruganti", "orduaorg", "cuanto", "shuanghuan", "brendanhoffmancom", "nvua", "marouane", "prueba", "recruited", "globallookpresscom", "httpsunianua", "pictwittercomofajfywf", "veroyatnocomua", "vsimua", "complaints", "wwwargumentuacom", "inua", "pictwittercomclmsrny", "medikforumru", "isrageowordpresscom", "accompanied", "structures", "quantities", "moveonorg", "pictwittercomlwrwff", "complicity", "itcua", "literaturzentrum", "continuation", "compelling", "httpkriminalictvua", "facebookcomsvobodupopugayu", "combustible", "youtubecomмакар", "championatcom", "combining", "httpcenznetcom", "httptwittercomictvchannel", "disrupt", "pictwittercomgpqpuiwo", "qualified", "rushing", "russisches", "frustrating", "darum", "wwwfacebookcomictvchannel", "chruchill", "httpsaftershocknewsqnod", 
                     "spiritual", "pictwittercomrlwyklze", "quattro", "commisso", "автоцентрua", "httpscontwskonors", "файнеua", "wwwtheplaceru", "facebookcomthenewarcorg", "httpspravdacomua", "complicated", "thorgan", "windrush", "httpictvua", "techcrunch", "prostotechcom", "jacomo", "eurosportru", "ruotsissa", "twittercomfutbolmatrix", "cual", "brutal", "annually", "recommendations", "equalise", "gordonuacom", "squads", "qualify", "wwwpravoslavieru", "httpswwwroiru", "communicate", "svabodaorg", "uan", "organised", "persuade", "recruitment", "newsweek", "youtubecom", "peru", "vringecom", "tehnofancom", "combat", "commemoration", "uatoday", "bevölkerung", "httpspublizistrublogs", "telecommunications", "situación", "virtual", "rund", "httpwwwvestifinanceruarticles", "instagramcomprykhodkoofficial", "intellectually", "httpwwwgeonamesorg", "ageofcompinfo", "highquality", "rupiah", "complaint", "dailyhororu", "liferu", "unewscomua", "comedy", "warum", "ammanbeirut", "situations", "guatemala", "competencia", "aurum", "httpnovorosinformorg", "biokoncomua", "newsmirinfo", "facebookcomvitaliiovcharenko", "wwwvringecom", "vigorcosmeticscom", "sportru", "irenbukurcomua", "coastguard", "illusoruacom", "aromatikaua", "rus", "soapfantasycomua", "combo", "changeorg", 
                     "thyssenkrupps", "dtpkyivua", "httpsitestwlocationprotocol", "competitiveness", "squadron", "uah", "joshua", "rulers", "httpsconnectfacebooknetukuasdkjsxfbmlversionv", "facebookcomulanasuprun", "bukpravdacvua", "russlands", "wwwadvocatconsinfo", "kaetanaua", "telecom", "uncomfortable", "pictwittercomiblyllrubr", "elfaua", "pielcosmeticscom", "uaперш", "httpstcogltrbamlx", "reforger", "trumpkim", "rsportriaru", "equality", "penaua", "commentsua", "uspixua", "struggling", "ruben", "components", "parimatchua", "pictwittercomoqbfewnrf", "ubrua", "organized", "instruments", "organizers", "guarantee", "lithuania", "combine", "telecommunication", "grudge", 
                     "guantanamo", "instagramcomlobodaofficial", "instagramcomanitasporty", "instagramcomlesianikituk", "equaliser", "apostropheua", "fruit", "kievinformatorua", "cualquier", "compete", "quattroporte", "marquardt", "organic", "instagramcomliliiarebrik", "darunter", "expresua", "sportexpressua", "composed", "facebookcom", "rusal", "comedian", "ofdru", "compensation", "cvnpugovua", "mailru", "sportsru", "comprehensive", "welcomed", "commons", "agroportalua", "complained", "facebookcomirinagalay", "httpscontws", "instagramcompolyakovamusic", "isportua", "stranaua", "bengaluru", "guards", "httpstwittercomcrimeauastatus", "inadequate", "subaru", "compañía", "vladtimeru", "instagramcomkosadcha", "molbukua", "rui", "compliance", "gamebetnews", "unusual", "httpscensor", "rush", "tiguan", "httprtbrvuacompanytele", "jerusalem", "drugs", "bruce", "uruguays", "maxgalkinru", "httpswwwinstagramcomuarivne", "qualifying", "httpstwittercomuarivnelanguk", "instagramcomelisvitolina", "commissioner", "juan", "httpswwwfacebookcomuarivnetv", "novostinorg", "kyivnpugovua", "httpstmeuarivnetv", "regierung", "stratcom", "httpservermedisumcomuampphpidtkzikmp", "tsnua", "httpswwwyoutubecomuserpodtpk", "facebookcomlivechernihiv", "structure", "rumbo", "instagramcomannasedokova", "commenthover", "trucks", "donbassua", "manual", "httpswwwfacebookcomfaktyictv", "httpictvuauaindexonline", "подробностиua", "segodnyaua", "quarters", "znua", 
                     "zagonkaru", "struggles", "ruporzt", "httpservermedisumcomuampphpiduapershiiymp", "facebookcomgroupsтипичн", "lamborghini", "luang", "anticorruption", "batshuayi", "pixabaycom", "morgan", "unncomua", "igual", "sportexpressru", "commercial", "instagramcomanilorak", "combined", "$bexclusivenewsmore", "newspapers", "wwwukrinformru", "lentaru", "nikopolnews", "ruotsin", "httpstmeaifukraine", "newsrucom", "forget", "footballua", "newsyou", "equal", "inequality", "yuan", "guard", "grupos", "httpscensornetua", "parubiy", "competing", "computer", "rusinfomailru", "shutterstockcom", "dsnsgovua", "аифua", "newsnetwork", "squad", "grupo", "comfortable", "obozrevatelcom", "scrutiny", "instagramcomreginatodorenko", "russians", "forumom", "новостейcom", "cruiser", "instagramcomjuliaroberts", "goalcom", "facebookcomkyivoperativ", "comply", "usual", "telegrafcomua", "httpservermedisumcomuampphpidtkkanalmp", "combination", "leopolisnews", "completed", "corrupt", "meteogovua", "casualties", "communist", "httpservermedisumcomuampphpidtkictvmp", "upcoming", "companys", "gottstatgmailcom", "newsroom", "individuals", "organisations", "commitments", "quarterfinal", "georgia", "truck", "cuartos", "wwwnewcinfo", "organización", "httpservermedisumcomuampphpidtrkukranamp", "commitment", "twittercomkrimrt", "intellectual", "arundel", "httppolitikusru", "cruel", "crucial", "headquarters", "facebookcomruslanalyzhychko", "guacho", 
                     "httpstvuan", "drug", "terrikoncom", "communication", "uafootball", "ruled", "tvua", "odessacom", "cuatro", "quarterfinals", "commander", "znajua", "truce", "тснua", "struggle", "httpservermedisumcomuampphpidtkintermp", "actual", "vistanews", "quality", "virtually", "goodnewsua", "httpstwittercomespresotv", "httpespresotv", "stylerrbcua", "ukrnewsnet", "uafootballcom", "language", "sexual", "httpespresotvmobile", "ruslan", "lodagovua", "httpswwwfacebookcomespresotv", "konkurentinua", "george", "commerce", "organizations", "jorge", "truth", "competitive", "wwwunncomua", "outcome", "httpdannewsinfo", "income", "rural", "russischen", "destruction", "fifacom", "communications", "eventually", "pixabaycommaggyona", "thyssenkrupp", "httpfriendmfagovua", "completely", "instagramcomkamenskux", "mednews", "companion", "infrastructure", "russische", "organisation", "httptripadvisormfagovua", "trudeau", "complete", "consormfagovua", "complex", "realdonaldtrump", "quarter", "compared", "trust", "ruposters", "rules", "httpscontwsanddan", "square", "committed", "corruption", "gorgany", "facebookcomigorzinkevych", "crude", "individual", "january", "structured", "qualcomm", "suarez", "communities", "lbua", "jaguar", "huawei", "construction", "february", "runs", "rusia", "competition", "uabbb", "cuando", "cndsnsgovua", "onlineua", "struggled", "brussels", "wwwgloballookpresscom", "newspaper", "uruguay", "russland",
                     "international", "financeua", "news", "people", "як", letters, stopwords("english"), stopwords("russian"), stopwords("german"), stopwords("SMART")))

stopwords <- stopwords[nchar(stopwords) < 20]
stopwords <- str_c("\\b", stopwords, "\\b", collapse="|")

#paste0("( ", paste(stopwords, collapse = " | "), " )")

text.clean = function(x) {
  x %>%
    str_to_lower() %>% 
    str_replace_all("<.*?>", " ") %>% 
    str_remove_all("[”–«°‘…‼¿¡—·الروس’―“>~−’º»«é‑‒\u0097\u0092`º´∫∑☀️▶️δ☬°☺®©●<|÷≈⇒↓×↑±→˚⇧+=]") %>% 
    str_replace_all("[:digit:]", " ") %>% 
    str_replace_all('\\w{20,}', " ") %>% 
    str_replace_all("^\\s+|\\s+$", " ") %>% 
    str_replace_all("[:punct:]", " ") %>%
    str_replace_all(stopwords, " ") %>%
    tm::stemDocument(language = "russian") %>% 
    str_squish()
}

train_lda <- function(text,caption,k){
  it_train = itoken(text.clean(text), 
                    preprocessor = tolower, 
                    ids = 1:length(text), 
                    progressbar = T)
  vocab = create_vocabulary(it_train,stopwords = stopwords)
  
  pruned_vocab = prune_vocabulary(vocab, 
                                  term_count_min = 5, 
                                  doc_proportion_max = 0.5,
                                  doc_proportion_min = 0.0001)
  
  vectorizer = vocab_vectorizer(pruned_vocab)
  
  dtm_train  = create_dtm(it_train, vectorizer)
  
  lda_model = LDA$new(n_topics = k)
  
  doc_topic_distr = 
    lda_model$fit_transform(x = dtm_train, n_iter = 2000, 
                            convergence_tol = 0.001, n_check_convergence = 25, 
                            progressbar = T)
  
  gammaDF <- as_tibble(doc_topic_distr)
  names(gammaDF) <- c(1:k)
  
  toptopics <- tibble(theme = as.numeric(apply(gammaDF, 1, function(x) names(gammaDF)[which(x == max(x))][1])),
                      theme_quality = apply(gammaDF, 1, max))
  
  tem <- bind_cols(data_frame(caption,text),toptopics)
  slov <- left_join((tem %>% 
                       group_by(theme) %>% 
                       summarise(theme_quality = max(theme_quality)[1])), tem[-2], by = c("theme_quality", "theme")) %>% 
    rename("theme2" = "caption")
  left_join(tem, (slov[!duplicated(slov[,'theme']),] %>% select(theme, theme2)), by = c("theme")) %>% 
    select(-theme) %>% 
    rename("theme" = "theme2")
}
